---
sidebar: sidebar
permalink: alert_data.html
keywords: alert, Critical, Warning, Low, Synopsis, Time range, Start time, End time, user 
summary: alerts page 
---

= Alerts

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media

[.lead]

The Alerts page shows all alerts generated by Cloud Secure. 

Use this page to identify recent alerts and the users generating the most alerts. 

You can also access all alerts that have been raised with the ability to drill down into individual alerts. 

== History

History shows the number of alerts that have been raised over the last seven days. Hovering over the severity of the alerts displays the number, severity, and occurrence date for each alert type.  

== Notable Users 

* Shows a list of the users that have generated the highest number of alerts.

* Shows the type of alerts generated.

* Shows the total number of alerts generated for each user. 

== Alert

The Alert list shows the total number of alerts that have been raised and contains details of all alerts:

* The date and time the alert was detected. 

* The status of the alert:

** New
** In Progress
** Resolved
** Dismissed
+
New is set by the by Cloud Secure. Administrators set all other status states, and add notes. 

*The User that raised the alert and a link to the User Profile

* The severity of the alert:  

** Critical

** Warning 

** Low 

* Synopsis identifies the activity that raised the alert and the user and community responsible. 
+
Click the link to drill down to the link:alert_detail[Alert Details and Related User] for detailed information.  

* Action Taken
+
Can include None, Quarantined, or Dismissed. 

Filter Options 

You can filter Alerts by the following:

* Action Taken
* Alert Type
* Note
* Severity
* Status
* Synopsis
* User
