---
sidebar: sidebar
permalink: cloud_insights_editions.html
summary: Cloud Insights is available in several different editions.
keywords: subscribe, trial, subscription, contract, editions, basic, standard
---

= Cloud Insights Editions

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The features and functionality available to you in Cloud Insights depend on the edition to which you subscribe. The editions available are explained here.

NOTE: The features, data retention times, and objects or metrics collected in the different Cloud Insights Editions are subject to change with or without notice. 

== Editions

After your free trial period, Cloud Insights is available in one of these Editions:

* *Basic Edition* is free and available to existing NetApp customers with an active NetApp support account.
* *Standard Edition* is available via subscription and offers all the features of Basic Edition plus:

** Increased data retention time to 90 days
** Monitoring of assets and performance
** Access to knowledgeable technical support staff.

==== Key Features

Here are some of the key features available in each Edition:

[cols=".<,.^,.^"]
|===
|Key Feature |Basic Edition |Standard Edition

|Data Retention|7 Days|*90* Days
|Infrastructure & Storage Metrics|&check; |&check; 
|VM Metrics|&check; |&check; 
|Cloud Metrics|&check; |&check; 
|Metrics from Over 50 Services|&check; |&check; 
|Topology|&check; |&check; 
|Customizable Dashboards|&check; |&check; 
|Monitoring|X|&check; 
|===

[cols=".<,.^,.^"]
|===
|Service & Support|Basic Edition |Standard Edition

|Community Forums|&check; |&check; 
|Online Documentation & Knowledgebase|&check; |&check; 
|Technical Support|X|&check; 
|===



