---
sidebar: sidebar
permalink: concept_cs_api.html
keywords: api, access, token, swagger  
summary: Cloud Secure includes a powerful API for integration with other applications such as CMDBs.
---

= Cloud Secure API

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Cloud Secure API enables NetApp customers and independent software vendors (ISVs) to integrate Cloud Secure with other applications, such as CMDB’s or other ticketing systems.

Requirements for API Access:

*	An API Access Token model is used to grant access.
*	API Token management is performed by Cloud Secure users with the Administrator role.


== API Documentation (Swagger)
The latest API information is found by logging in to Cloud Secure and navigating to *Admin > API Access*. Click the *API Documentation* link.
The API Documentation is Swagger-based, which provides a brief description and usage information for the API and allows you to try it out in your environment.

== API Access Tokens
Before using the Cloud Secure API, you must create one or more *API Access Tokens*. Access tokens grant read permissions. You can also set the expiration for each access token. 

To create an Access Token:

* Click *Admin > API Access*
*	Click *+API Access Token*
*	Enter *Token Name*
*	Specify *Token Expiration*

NOTE: Your token will only be available for copying to the clipboard and saving during the creation process. Tokens can not be retrieved after they are created, so it is highly recommended to copy the token and save it in a secure location. You will be prompted to click the Copy API Access Token button before you can close the token creation screen.

You can disable, enable, and revoke tokens. Tokens that are disabled can be enabled.

Tokens grant general purpose access to APIs from a customer perspective, managing access to APIs in the scope of their own environment. 

The application receives an Access Token after a user successfully authenticates and authorizes access, then passes the Access Token as a credential when it calls the target API. The passed token informs the API that the bearer of the token has been authorized to access the API and perform specific actions based on the scope that was granted during authorization.

The HTTP header where the Access Token is passed is *X-CloudInsights-ApiKey:*

For example, use the following to retrieve storages assets:

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
 
Where _<API_Access_Token>_ is the token you saved during API access key creation.

Detailed information can be found in the _API Documentation_ link under *Admin > API Access*. 


