---
sidebar: sidebar
permalink: concept_asset_summary_section.html
summary: Overview of the asset page Summary section in Cloud Insights.
keywords: asset, summary, landing page
---

= Asset Page Summary section

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The Summary section of an asset page displays general information about an asset, including whether any metrics or performance policies are cause for concern. Potential problem areas are indicated by a red circle next to the metric or performance policy.

image:

Note: The information displayed in the Summary section varies, depending on the type of asset you are viewing.

You can click any of the asset links to view their asset pages. For example, if you are viewing a storage node, you can click a link to view the asset page of the storage it is associated with.

You can view the metrics associated with the asset. A red circle next to a metric indicates that you might need to diagnose and resolve potential problems.

NOTE: You may notice that volume capacity might show greater than 100% on some storage assets. This is due to metadata related to the capacity of the volume being part of the consumed capacity data reported by the asset.

If applicable, you can click a performance policy link to view the performance policy or policies associated with the asset. 
If a red circle appears next to a performance policy, this indicates an asset has crossed the performance policy's defined threshold. You can examine the performance policy to further diagnose the issue.
