---
sidebar: sidebar
permalink: concept_telegraf_display_options.html
keywords: telegraf, data, display, 
summary: Telegraf data display options 
---


= Custom Metric Display Options

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
The Cloud Insights data collectors are powerful tools for gathering source-reported metrics from your data sources. You can transform the data to display it in a number of ways.

Cloud Insights provides different transform options for metrics in widgets, allowing you to display it in a number of ways. When adding transformable metrics to a widget, you are presented with a drop-down giving the following transform choices:

None::
Data is displayed as is, with no manipulation.

Rate::
Current value divided by the time range since the previous observation.

Cumulative::
The accumulation of the sum of previous values and the current value.

Delta::
The difference between the previous observation value and the current value. 

Delta rate::
Delta value divided by the time range since the previous observation.

Cumulative Rate::
Cumulative value divided by the time range since the previous observation.
 



