---
sidebar: sidebar
permalink: concept_subscribing_to_cloud_insights.html
summary: At any point during your free trial, you can subscribe to Cloud Insights.
keywords: subscribe, trial, sunscription, contract
---

= Subscribing to Cloud Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help, onboarding, getting started

[.lead]
At any point during your free trial of Cloud Insights, you can subscribe. Subscribing to Cloud Insights ensures uninterrupted access to your data as well as extended product link:https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html[support] options.

Ther are two modes of access to Cloud Insights:
* Trial Mode
* Subscription Mode

== Trial Mode
When you sign up for Cloud Insights and your instance is active, you enter into a free, 14-day Trial of Cloud Insights. During this trial you can explore all the features that Cloud Insights has to offer. 

At any time during your trial period, you can subscribe to Cloud Insights. To subscribe, go to *Admin > Subscribe*.

NOTE: You must be an Account Owner or Administrator in order to subscribe to Cloud Insights. Additionally, you must have an Amazon Web Services (AWS) account with the same email address as your Cloud Insights Account Owner or Administrator login.


== Subscription Mode

Notes:
Cancel subscription (within 48 hours) - Amazon
Go to Support Page (Amazon) to cancel subscription


== What is a *Managed Unit*?

A Managed Unit (MU) is the unit of measurement by which Cloud Insights is priced. Managed Unit use is calculated based on the number of _hosts_ and amount of _raw storage capacity_ being managed in your infrastructure environment.

* 1 Managed Unit = 1 host (any virtual or physical machine)
* 1 Managed Unit = 5 TB of raw storage capacity

