---
sidebar: sidebar
permalink: concept_requesting_support.html
summary: You can view knowledgebase articles, connect with the NetApp community, view videos, or open a ticket to request support.
keywords: support, knowledgebase, documentation, community, chat, videos, help, contact
---

= Requesting Support

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Support for Cloud Insights is available in a variety of ways. You can search for knowledgebase (KB) articles, connect with the NetApp community, watch videos, get sales and pre-sales assistance, and open a support ticket.

NOTE: You must register in order to activate support for NetApp Cloud products. To register, go to NetApp's link:https://register.netapp.com[Cloud Data Services Support Registration].

== Ways to receive support:

* *Knowledgebase*
+
Clicking on these links takes you to the NetApp Knowledgebase, where you can search for articles related to your request.

* *Documentation*
+
Clicking on the Documentation link takes you to this documentation center.

* *Community*
+
Clicking on the community link takes you to the Netapp community, where you can connect with peers and experts.

* *Videos*
+
Allows you to find and view videos related to Cloud Insights.

== Contacting Support

If you are requesting technical support, it is highly recommended that you check the box to allow a NetApp Support Engineer to have access to your Cloud Insights tenant during your support session.  This will allow them to troubleshoot the problem and help you resolve it quickly. When your issue is resolved or your support session has ended, you can un-check the box. 

You can request support by any of these methods:

* Chat
* Phone
* Opening a Support Ticket

You can also request sales or pre-sales support by clicking on the Sales Support link.


