---
sidebar: sidebar
permalink: concept_acquisition_unit_requirements.html
summary: The server or VM you use as your Acquisition Unit must meet minimum requirements
keywords: AU, acquisition unit, RAU, requirements, sizing
---

= Acquisition Unit Requirements
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must install an Acquisition Unit (AU) in order to acquire information from your infrastructure data collectors (storage, VM, port, EC2, etc.). Before you install the Acquisition Unit, you should ensure that your environment meets operating system, CPU, memory, and disk space requirements.

== Requirements

|===
|Component | Linux Requirement | Windows Requirement
|Operating system	
|A computer running a licensed version of one of the following:

* Centos (64-bit): 7.2 through 7.9, Stream 8, Stream 9
* Debian (64-bit): 9 and 10
* Oracle Enterprise Linux (64-bit): 7.5 through 7.9, 8.1 through 8.4
* Red Hat Enterprise Linux (64-bit): 7.2 through 7.9, 8.1 through 8.7, 9.1
* Rocky 9.0, 9.1
* Ubuntu Server: 18.04 and 20.04 LTS

This computer should be running no other application-level software. A dedicated server is recommended. 

|A computer running a licensed version of one of the following:

* Microsoft Windows 10 64-bit
* Microsoft Windows Server 2012
* Microsoft Windows Server 2012 R2
* Microsoft Windows Server 2016
* Microsoft Windows Server 2019
* Microsoft Windows Server 2022
* Microsoft Windows 11

// * Microsoft Windows 11 64-bit
// * Microsoft Windows 2022

This computer should be running no other application-level software. A dedicated server is recommended. If you have a larger environment, it is recommended to have more storage space.
|CPU	|2 CPU cores 
| Same
|Memory	|8 GB RAM 
| Same
|Available disk space	|50 GB (100 GB recommended)
For Linux, disk space should be allocated in this manner:
/opt/netapp 10 GB (20 GB for large environments)
/var/log/netapp 40 GB (80 GB for large environments)
/tmp at least 1 GB available during installation
|50 GB
|Network	|100 Mbps/1 Gbps Ethernet connection, static IP address, and port 80 or 443 connectivity from Acquisition Unit to *.cloudinsights.netapp.com or your Cloud Insights environment (i.e. \https://<environment_id>.c01.cloudinsights.netapp.com) is required. For requirements between Acquisition Unit and each Data Collector, please refer to instructions for the link:data_collector_list.html[Data Collector].

If your organization requires proxy usage for internet access, you may need to understand your organization’s proxy behavior and seek certain exceptions for Cloud Insights to work. For example, does your organization block access by default, and only allow access to specific web sites/domains by exception? If so, you will need to get the following domain added to the exception list:

*.cloudinsights.netapp.com

For more information, ready about Proxies link:task_troubleshooting_linux_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls[here] or link:task_troubleshooting_windows_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls[here].

|Same 
|Permissions	|Sudo permissions on the Acquisition Unit server.  
/tmp must be mounted with exec capabilities.
|Administrator permissions on the Acquisition Unit server
|Virus Scan |  | During installation, you must completely disable all virus scanners. Following installation, the paths used by the Acquisition Unit software must be excluded from virus scanning.
|===

////  
OLD STYLE:
* CentOS 7.2 64-bit
* CentOS 7.3 64-bit
* CentOS 7.4 64-bit
* CentOS 7.5 64-bit
* CentOS 7.6 64-bit
* CentOS 7.7 64-bit
* CentOS 7.8 64-bit
* CentOS 7.9 64-bit
* CentOS 8.1 64-bit

* Debian 9 64-bit

* Oracle Enterprise Linux 7.5 64 bit
* Oracle Enterprise Linux 7.6 64 bit
* Oracle Enterprise Linux 7.7 64 bit
* Oracle Enterprise Linux 7.8 64 bit
* Oracle Enterprise Linux 7.9 64 bit
* Oracle Enterprise Linux 8.1 64 bit

* Red Hat Enterprise Linux 7.2 64-bit
* Red Hat Enterprise Linux 7.3 64-bit
* Red Hat Enterprise Linux 7.4 64-bit
* Red Hat Enterprise Linux 7.5 64-bit
* Red Hat Enterprise Linux 7.6 64-bit
* Red Hat Enterprise Linux 7.7 64-bit
* Red Hat Enterprise Linux 7.8 64-bit
* Red Hat Enterprise Linux 7.9 64-bit
* Red Hat Enterprise Linux 8.1 64-bit

* Ubuntu Server 18.04 LTS
////

== Additional recommendations
* For accurate audit and data reporting, it is strongly recommended to synchronize the time on the Acquisition Unit machine using *Network Time Protocol (NTP)* or *Simple Network Time Protocol (SNTP)*.

== Regarding Sizing

You can get started with a Cloud Insights Acquisition Unit with just 8GB memory and 50GB of disk space, however, for larger environments you should ask yourself the following questions: 

Do you expect to:

* Discover more than 2500 virtual machines or 10 large (> 2 node) ONTAP clusters, Symmetrix, or HDS/HPE VSP/XP arrays on this Acquisition Unit?
* Deploy 75 or more total data collectors on this Acquisition Unit?

For each "Yes" answer above, it is recommend to add 8 GB of memory and 50 GB of disk space to the AU. So for example if you answered "Yes" to both, you should deploy a 24GB memory system with 150GB or more of disk space. On Linux, the disk space to be added to the log location.

For additional sizing questions, contact NetApp Support.

== Additional Federal Edition requirement

* For Acquisition Unit installations in Cloud Insights Federal Edition clusters, the underlying operating system must have a good source of entropy. On Linux systems this is typically done by installing _rng-tools_ or by using hardware random number generation (RNG). It is the customer's responsibility to ensure this requirement is met on the Acquisition Unit machine.




