---
sidebar: sidebar
permalink: concept_cs_event_rate_checker.html
summary: This script  can be run to check the event rate in the SVM before installing an ONTAP SVM DSC
keywords: event, checker, rate, sizing
---

= SVM EVENT RATE CHECKER FOR SIZING AGENT MACHINE

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]


1.	This script  can be run to check the event rate in the SVM before installing an ONTAP SVM DSC. When running this script no ONTAP SVM Data Collector should be running for the SVM for which event rate is being determined.
2.	This check is to see how many SVMs one Agent machine will be able to monitor.
3.	Please keep Cluster IP, cluster admin username, cluster admin password handy before running the script.
4.	To run the script, as a first step, install the Agent by following the instructions in CloudSecure.
5.	Once agent is installed, run the following file present in this directory as a sudo user /opt/netapp/cloudsecure/agent/install/vserver_data_rate_checker.sh
6.	Run the script, provide the correct values in the prompts when the script runs. See below how the script can be run.
7.	The script will run for 5mins and after that it will automatically stop.
8.	After the run is complete, the script will print the event rate from the SVM, please check Event rate per SVM in the console output.

“Svm svm_rate is generating 100 events/sec”. 

This will show what is the rate of generation of Events for a SVM.
9.	1 Ontap SVM Data Collector can be associated with 1 SVM. So it means 1 SVM DataCollector will be able to receive the number of events which SVM generates.
10.	A)A single Agent machine can handle upto 7000events/second and max of 10 data collectors.
B)Please add up the Events being generated for all the SVMs and add it together.

C)If the script is not run during peak hours or if peak traffic is difficult to predict, then keep an event rate buffer of 30%.
(B) + (C) Should be less than (A), otherwise the Agent machine will fail to monitor.

The number of data collectors which can be added to 1 Agent box, should comply to the formula given below:

Sum of all Event rate of all Data Source Collectors which will be installed in 1 Agent Machine + Buffer Event rate of 30% < 7000events/second.

For example: In the example below, following are the event rates of the SVMs 100,200,300 event/sec
So applying the formula:
(100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec

780events/sec is <  7000events/sec, hence the 3SVMs can be monitored via one agent box.

11.	Also the console output is available in the Agent machine in the file name fpolicy_stat_<SVM Name>.log in the present working directory. 
12.	The script may give erroneous results in the following cases:
a.	If provided wrong credentials, IP address or wrong SVM name.
b.	Already existing fpolicy with same name/sequence number etc will give error.
c.	The script is stopped abruptly in between.

13.	Example output is shown below:
[root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2

-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip): QA_SVM
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Running check for svm QA_SVM...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
Stopping sample QA_SVM_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm shails3 is generating 200 events/sec
fpolicy stats of svm QA_SVM is saved in fpolicy_stat_QA_SVM.log
Svm QA_SVM is generating 300 events/sec
[root@ci-cs-data agent]#

