---
sidebar: sidebar
permalink: concept_audit.html
keywords: audit, users, activities
summary: Audit provides a view of system and user activities in the Cloud Insights system.
---

= Auditing

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To identify changes both expected (for tracking) or unexpected (for troubleshooting), you can view an audit trail of the Cloud Insights system events and user activities.

== Viewing Audited Events

To View the Audit page, click *Admin > Audit* in the menu. The Audit page is displayed, providing the following details for each audit entry:

* *Time* - Date and time of the event or activity
* *User* - The User who initiated the activity 
* *Role* - The user's role in Cloud Insights (guest, user, administrator)
* *IP* - The IP address associated with the event
* *Action* - Type of activity, for example Login, Create, Update
* *Category* - The category of activity
* *Details* - Details of the activity

When there is a user activity that affects a resource, such as a data collector or an application, the details include a link to the resource's landing page.

*Note* When a data collector is deleted, the user activity details related to the data collector no longer contain a link to the data collector's landing page.

== Displaying audit entries

There are a number of different ways to view audit entries:

* You can display audit entries by choosing a particular time period (1 hour, 3 hours, 24 hours, 3 days, and 7 days), with Cloud Insights showing a maximum number of 1000 violations for the selected time period.

* You change the sort order of the columns in a table to either ascending (up arrow) or descending (down arrow) by clicking the arrow in the column header.
+
By default, the table displays the entries in descending time order.

* You can use the filter box to show only the entries you want in the table.

== Audited Events and Actions

The events and actions audited by Cloud insights can be categorized in the following broad areas:

* User account: Log in, log out, role change, etc.
+
Example: _User *Tony Lavoie* logged in from *10.1.120.15*, user agent *Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36*, login method(s) *Cloud Central Portal Login*

* Acquisition Unit: create, delete, etc.
+
Example: _Acquisition unit *AU-Boston-1* removed_

* Data Collector: add, remove, modify, postpone/resume, change acquisition unit, start/stop, etc.
+
Example: _Datasource *FlexPod Lab* removed, vendor *NetApp*, model *ONTAP Data Management Software*, ip *192.168.106.5*_

* Application: add, assign to object, remove, etc.
+
Example: _Internal Volume *ocisedev:t1appSVM01:t1appFlexVol01* added to application *Test App*_

* Annotation: add, assign, remove, annotation rule actions, annotation value changes, etc.
+
Example: _Annotation value *Boston* added to annotation type *SalesOffice*_

* Query: add, remove, etc.
+
Example: _Query *TL Sales Query* is added_

* Monitor: add, remove, etc.
+


* Notification: change email, etc.
+






