---
sidebar: sidebar
permalink: concept_subscribing_to_cloud_insights.html
summary: At any point during your free trial, you can subscribe to Cloud Insights.
keywords: subscribe, trial, sunscription, contract
---

= Subscribing to Cloud Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help, onboarding, getting started

[.lead]
At any point during your free trial of Cloud Insights, you can subscribe. Subscribing to Cloud Insights ensures uninterrupted access to your data as well as extended product link:https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html[support] options.

Ther are two modes of access to Cloud Insights:
* Trial Mode
* Subscription Mode

== Trial Mode
When you sign up for Cloud Insights and your instance is active, you enter into a free, 14-day Trial of Cloud Insights. During this trial you can explore all the features that Cloud Insights has to offer. 

At any time during your trial period, you can subscribe to Cloud Insights. To subscribe, go to *Admin > Subscribe*.

NOTE: You must be an Account Owner or Administrator in order to subscribe to Cloud Insights. Additionally, you must have an Amazon Web Services (AWS) account with the same email address as your Cloud Insights Account Owner or Administrator login.

Cloud Insights will display a banner when your free trial is nearing its end. Within that banner is a link to the Subscription page. Non-Admin users will see the banner but will not be able to go to the Subscription page.

If your free trial has expired and you have not yet subscribed to Cloud Insights, you will have limited functionality until you subscribe. Your data will still be collected for 14 days after the end of your trial, in order to ensure non-interrupted flow until your subscription is active. After 14 days, if you have not subscribed, Cloud Insights will stop collecting data.



Can extend only once.

When expired, user can ONLY see "you are expired" admin > subscription page.
Admin sees subscription calculator and "Subscribe Now" page.
When trial expired, Cloud Insights still collects data for 14 days, to allow customer time to subscribe.
All functions are disabled (Admin can get to DC and Subscription pages)
Admin can delete or modify existing data (DC), but not create.

Subscribe Now button takes you to AWS subscribe page

Data Collector MU's are rounded up. 
Total MU's is also rounded up. 
DC MU's may be more than total MU's because of this rounding
(Edwin's example - 138 when add all DC MU's, but Total used is 137)

Info entered in the calculator is NOT saved and populated in the AWS subscribe page

Once subscribed on AWS, takes us back to the gateway

Must complete subscription flow within one hour
Message (token expired, go to setup and complete subscription) - can I see exact message?



== Subscription Mode


Notes:
Cancel subscription (within 48 hours) - Amazon
Go to Support Page (Amazon) to cancel subscription

View Data Collector details on subscription page
Count of MU's per data collector
Count may not match "Total" MU's
Can delete data collectors in this list



== What is a *Managed Unit*?

A Managed Unit (MU) is the unit of measurement by which Cloud Insights is priced. Managed Unit use is calculated based on the number of _hosts_ and amount of _raw storage capacity_ being managed in your infrastructure environment.

* 1 Managed Unit = 1 host (any virtual or physical machine)
* 1 Managed Unit = 5 TB of raw storage capacity

