---
sidebar: sidebar
permalink: concept_getting_started_checklist.html
summary: Cloud Insights has tutorials to show you how to perform many tasks.
keywords: onboarding, getting started, video, tutorial, 
---

= Getting Started Checklist

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Insights is loaded with useful features that enable you to quickly and easily find data, troubleshoot issues, and present insights into your corporate environment. Find data easily with powerful queries, visualize data in dashboards, and send email alerts at data thresholds you set. 

Video tutorials can help you understand these features and better implement your business insights strategies. Every user who has access to your Cloud Insights environment can take advantage of these tutorials.

== Checklist and Video Tutorials

The *Getting Started* checklist displayed on your Cloud Insights site contains a list of several useful tasks and concepts. Selecting an item in the checklist takes you to the appropriate Cloud Insights page for that concept. For example, clicking on the "Create a Dashboard" item opens the Cloud Insights *Dashboards* page.

At the top of the page is a link to a video tutorial showing how to create a dashboard. Click the _Watch Video_ button to view the tutorial. You can view the video as many time as you like until you click the "Got it! Don't Show This Again" link for that video. The video is available every time you go to the Dashboards page, until you dismiss it.

After watching the video at least once, the "Create a Dashboard" item in the checklist is checked off, indicating that you have completed the turorial. You can then proceed to the next tutorial.

NOTE: You can view the tutorials in any order you like. 

The "Getting Started" checklist is displayed on your site until you click the "Don't Show This Again" link at the bottom of the checklist. Even after dismissing the checklist, the tutorials are still available on each appropriate Cloud Insights page until you dismiss each one.

NOTE: Once you dismiss the checklist, you will not be able to display it again.
