---
sidebar: sidebar
permalink: concept_whats_new.html
summary: New features and functionlity in Cloud Insights.
keywords: features
---

= What's New with Cloud Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
NetApp is continually improving and enhancing its products and services. Here are some of the latest features and functionalities available with Cloud Insights.

=== *February 2019*

==== Getting Started Checklist and Video Turorials

Video turorials are available for a number of common Cloud Insights features and concepts. Videos are available for Dashboards, Queries, Policies, and more, and each video can be viewed many times until dismissed. The Checklist keeps track of which tutorials you have viewed. 

==== Acquisition Unit for Windows

* You can configure a Cloud Insights Acquisition Unit on a Windows server/VM. Review the Windows link:concept_acquisition_unit_requirements.html[pre-requisites] before installing the link:task_configure_acquisition_unit.html[Acquisition Unit software].


=== *January 2019*

////
==== "Subscription ID" is now "Subscription Name"

* On the *Admin > Subscription* and *Help > Support* pages, the field for "NetApp Subscription ID" has been renamed to "NetApp Subscription Name" for readability.  The data in the field remains as it was.
////

==== "Owner" field is more readable

* In Dashboard and Query lists, the data for the "Owner" field was previously an authorization ID string, instead of a user-friendly owner name. The "Owner" field now shows a simpler and more readable owner name.

==== Managed Unit Breakdown on Subscription Page

* For each data collector listed on the *Admin > Subscription* page, you can now see a breakdown of Managed Unit (MU) counts for hosts and storage, as well as the total.


=== *December 2018*

==== Improvement of UI Load Time

* The initial loading time for the Cloud Insights user interface (UI) has been significantly improved. Refresh time for the UI also benefits from this improvement in circumstances where metadata is loaded.

==== Bulk Edit Data Collectors

* You can edit information for multiple data collectors at the same time. On the *Admin > Data Collectors* page, select the data collectors to modify by checking the box to the left of each and click the *Bulk Actions* button. Choose *Edit* and modify the necessary fields.
+
The data collectors selected must be the same vendor and model, and reside on the same Acquisition Unit.

==== Support and Subscription pages are Available During Onboarding

* During the onboarding workflow, you can navigate to the *Help > Support* and *Admin > Subscription* pages. Returning from those pages returns you to the onboarding workflow, providing you have not closed the browser tab.

=== *November 2018*

==== Subscribe through NetApp Sales or AWS Marketplace

* Cloud Insights subscription and billing is now available directly through NetApp. This is in addition to the self-serve subscription available through AWS Marketplace. A new *Contact Sales* link is presented on the *Admin > Subscription* page. For customers whose environments have or are expected to have 1,000 or more Managed Units (MUs), it is recommended to contact NetApp sales via the Contact Sales link.

==== Text Annotation Hyperlinks

* Text-type annotations can now include hyperlinks. 

==== Onboarding Walkthrough

* Cloud Insights now features an onboarding walkthrough for the first user (administrator or account owner) to log in to a new environment. The walkthrough takes you through installing an Acquisition Unit, configuring an initial data collector, and selecting one or more useful dashboards.

==== Import Dashboards from the Gallery

* In addition to selecting dashboards during onboarding, you can import dashboards via *Dashboards > Show All Dashboards* and clicking *+From Gallery*.

==== Duplicating Dashboards

* The ability to duplicate a dashboard has been added to the dashboard list page as a choice in the options menu for each dashboard, and on a dashboard's main page itself from the _Save_ menu.

==== Cloud Central products menu

* The menu allowing you to switch to other NetApp Cloud Central products has moved to the upper right corner of the screen.


////
•	Windows AU support
•	IBG-15020: Allow quote characters in the invited user's email
•	[IBG-15082] Invite email - add note for Cloud Central account sign up
•	US35338: SaaS Gateway: Navigation to switch to other cloud products
•	US35261: Google Cloud Platform VM inventory
•	IBG-15085: Tenant service issues on upgrade of FAILED_CREATION
•	IBG-145072: updating raw capacity to unformatted capacity
•	Duplicating dashboard

•	[IBG-15042] Remove suffix from site name
•	IBG-15045: fix au deadlock in FilteredRemoteAppender
•	Billing: Subscription Update Job for all subscriptions
•	reshuffle persistent volumes and persistent volume claims
•	tweak mem size for level2 tenant profile
////



