---
sidebar: sidebar
permalink: concept_requesting_support.html
summary: You can view knowledgebase articles, connect with the NetApp community, view videos, or open a ticket to request support.
keywords: support, knowledgebase, documentation, community, chat, videos, help, contact
---

= Requesting Support

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp provides support for Cloud Insights in a variety of ways. Extensive free self-support options are available 24x7, such as knowledgebase (KB) articles, NetApp community, videos, etc. Customers with a paid Cloud Insights subscription can contact our knowledgeable Support Engineers via chat, phone, or web ticket.

NOTE: You must register in order to activate support for NetApp Cloud products. To register, go to NetApp's link:https://register.netapp.com[Cloud Data Services Support Registration].

You can access support options in Cloud Insights by clicking on *Help > Support*. The support options available to you depend on whether you are in Trial mode or Subscribed.

== Self-support:

These options are available for free 24x7:

* *Knowledgebase*
+
Clicking on these links takes you to the NetApp Knowledgebase, where you can search for articles related to your request.

* *Documentation*
+
Clicking on the Documentation link takes you to this documentation center.

* *Community*
+
Clicking on the community link takes you to the Netapp community, where you can connect with peers and experts.

* *Videos*
+
Allows you to find and view videos related to Cloud Insights.

== Subscribed Support

In addition to the self-support options above, if you have a Cloud Insights paid subscription and are requesting technical support, you can work with a NetApp Support Engineer to resolve your problem.

NOTE: It is highly recommended that you check the box to allow a NetApp Support Engineer to have access to your Cloud Insights tenant during your support session. This will allow the engineer to troubleshoot the problem and help you resolve it quickly. When your issue is resolved or your support session has ended, you can un-check the box. 

You can request support by any of these methods:

* Chat
* Phone
* Opening a Support Ticket

You can also request sales or pre-sales support by clicking on the Sales Support link.


