---
sidebar: sidebar
permalink: concept_insights_and_impacts.html
keywords: insights, greedy, degraded, bully, victim, impacted, impacting, impactful, impact, resources
summary: Insights give you a look into how resources impact other resources in your environment.
---

= Insights and Impacts

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Insights provides tools to help you investigate resource contention and impact in your invironment. 

=== Some terms to keep in mind

An _impactful_ or _greedy_ resource is one that causes a negative impact on another resource. For example, a volume experiencing very high IOPS may cause increased latency in other volumes (i.e. _impacted_ or _degraded_ resources). Impactful and Impacted resources are “peers” that utilize the same shared resource, for example, a storage pool or node. 

A _Changed Workload_ is a workload that is currently identified as impacting other resources in the shared storage pool. These workloads drive higher IOPS, reducing IOPS in the Impacted Workloads.

An _Impacted Workload_ is a workload affected by a changed workload in the shared Storage Pool. These workloads are experiencing reduced IOPS and/or higher latency, caused by the  Changed Workloads.

The _Shared Resource Contention Ratio_ is the ratio of impacting IOPS to baseline. 

_Baseline_ is defined as the maximum reported data point for each workload in the hour immediately preceding the contention. 

A _Contention_ occurs when IOPS are determined to be affecting other resources or workloads in the shared storage pool.



=== What do I do to resolve contentions?

There are a number of steps you can take to reduce or eliminate the chance of contentions in your environment. Here are a few things you can try.

* Move high-IOPS consumers
+
Move the "greedy" workloads to less-contended Storage Pools. It is recommended to assess the tier and capacity of these pools before moving the workloads, to avoid unnecessary costs or additional contentions.

* Implement a quality of service (QoS) policy
+
Implementing a QoS policy per workload to ensure enough free resources available will alleviate saturation on the Storage Pool. This is a long-term solution.

* Add additional resources
+
If the Storage Pool has reached the IOPS saturation point, adding more or faster disks to the pool will ensure enough free resources available to alleviate saturation.








