---
sidebar: sidebar
permalink: concept_user_roles.html
keywords: roles, users, guest, user, administrator
summary: There are multiple user accounts with different permission levels.
---

= User accounts

[.lead]
Cloud Insights provides four user accounts, Account Owner, Administrator, User, and Guest. Each account is assigned specific permission levels.

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

The following table identifies the permissions granted to each user account:

[cols=6*, options=header]

|===
|Menu
|Function
|Account Owner
|Admin
|User
|Guest
|Admin |Acquisition units - Add/Remove |Yes |Yes |No |No
|Admin|Data Collectors - Add/Modify/Remove |Yes |Yes |No |No
|Admin|Health Page - View |Yes |Yes |No |No
|Admin|Audit Page - View |Yes |Yes |No |No
|Account|Account/Users - Invite/Modify/Deactivate |Yes |Yes |No |No
|Dashboards|Dashboards - Create/Modify/Delete |Yes |Yes |Yes |No
|Dashboards|Dashboards - View |Yes |Yes |Yes |Yes
|Queries|Queries - Create/Modify/Delete |Yes |Yes |Yes |No
|Queries|Queries - View/Run |Yes |Yes |Yes |Yes
|Manage|Polocies - Create/Modify/Delete |Yes |Yes |No |No
|Manage|Policies - View |Yes |Yes |Yes |No
|Manage|Annotation - Create/Modify/Delete/Assign |Yes |Yes |Yes |No
|Manage|Annotation - View |Yes |Yes |Yes |No
|Manage|Annotation Rules - Create/Modify/Delete |Yes |Yes |Yes |No
|Manage|Annotation Rules - View |Yes |Yes |Yes |No
|Manage|Applications - Create/Modify/Delete |Yes |Yes |Yes |No
|Manage|Applications - View |Yes |Yes |Yes |No
|   -  |Asset Pages - Modify |Yes |Yes |Yes |No
|   -  |Asset Pages - View |Yes |Yes |Yes |Yes
|===

You use an account that has Administrator privileges to create or modify user accounts. Each user account is assigned one of the following permission levels.
* _Guest_ can view asset pages, dashboards, and queries, and can run queries.
* _User_ can perform all guest-level privileges, and create, modify, or delete dashboards, queries, annotations, annotation rules, and applications. Users cannot create, modify, or delete policies.
* _Admin_ and _Account Owner_ can perform all functions including adding new users and managing data collectors.

The Account Owner is created when you register for Cloud Insights. Only an Account Owner can assign the Account Owner role to another user. There must always be at least one Account Owner for a tenant.

Best practice is to limit the number of users with Administrator permissions. The greatest number of accounts should be user or guest accounts.
// <or Privs...get the wording straight.> 

== Creating user accounts
New accounts are initiated by inviting users to access the tenant.
// <sending a request for an account> 

.Before you begin
* Install your Cloud Insights licenses.
* If a user you wish to invite already has an account on the NetApp Cloud Portal, you should send the invite to the email address they used for that account.
// <* Allocate a unique user name for each user.>
// <* Determine what passwords to use.>
* Understand the user roles you will be assigning.

.Steps
. Log into Cloud Insights
. In the menu, click *Admin > Account Manager*
+
The User Management screen is displayed. The screen contains a list of all of the accounts on the system.
. Click *+ User*
+
The Invite User screen is displayed.
. Enter an email address or multiple addresses for invitations.
+
*Note:* When you enter multiple addresses, they are all created with the same role. You can only set multiple users to the same role.
. Enter the user's e-mail address.
. Select the user role.

. Click *Invite*.
+
The invitation is sent to the user. 
+
Users will have 14 days to accept the invitation. Once a user accepts the invitation, he or she will be taken to the NetApp Cloud Portal, where they will sign up using the email address in the invitation. If they have an existing account for that email address, they can simply sign in and will then be able to access the Cloud Insights tenant.

== Modifying a User's Role

To change a user's role:

.Steps
. Log in as an Administrator or an Account Owner and go to *Admin > Account Management*.
. Select a new role from the drop-down for the user. 

== Deactivating a User's Account

To deactivate a user's account:

.Steps
. Log in as an Administrator or an Account Owner and go to *Admin > Account Management*.
. Click on the "three dot" menu to the right of the user and select *Deactivate*.
