---
sidebar: sidebar
permalink: concept_querying_assets.html
summary: Querying Overview
keywords: query, queries, Application, Datastore, Disk, Fabric, Generic Device, Host, Internal Volume, iSCSI, Network, Portal, Path, Port, Qtree, Quota, Share, Storage, Node, Pool, SVM, Switch, Tape, VMDK, Virtual Machine, VM, Volume, Zone, Member
---

= Assets used in queries

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Queries enable you to monitor and troubleshoot your network by searching the assets in your environment at a granular level based on user-selected criteria (annotations and performance metrics). Additionally, annotation rules, which automatically assign annotations to assets, require a query.

The following asset types can be used in queries, dashboard widgets, and custom asset landing pages. The fields and counters available for filters, expressions, and display will vary among asset types. Not all assets can be used in all widget types.

* Application
* Datastore
* Disk
* Fabric
* Generic Device
* Host
* Internal Volume
* iSCSI Session
* iSCSI Network Portal
* Path
* Port
* Qtree
* Quota
* Share
* Storage
* Storage Node
* Storage Pool
* Storage Virtual Machine (SVM)
* Switch
* Tape
* VMDK
* Virtual Machine
* Volume
* Zone
* Zone Member
