---
sidebar: sidebar
permalink: concept_reporting_predefined_reports.html
summary: Overview of pre-defined reports
keywords: reporting, cognos, data warehouse, dwh, pre-defined
---

= Pre-defined Reports Made Easy

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can generate pre-defined reports from the Cloud Insights Reporting Portal, email them to other users, and even modify them. Several reports enable you to filter by device, business entity, or tier. The reporting tools use IBM Cognos as a foundation and give you many data presentation options.

The pre-defined reports show your inventory, storage capacity, chargeback, performance, storage efficiency, and cloud cost data. You can modify these pre-defined reports and save your modifications.

The report data available to you is controlled by several things, including the following:

* Login access to the OnCommand Insight Reporting Portal, which is defined by roles.
* The setup of the OnCommand Insight Data Warehouse, which stores the data for the reports.

You can generate reports in various formats, including HTML, PDF, CSV, XML, and Excel.

Cloud Insights accommodates multiple tenancy in reporting by enabling you to associate users with business units. With this feature, administrators can separate data or reports according to the attributes of a user or his/her affiliation.

== Navigating to Pre-defined Reports

When you open the Reporting Portal, the _Team Content_ folder is the starting point for you to select the type of information that you require in the Cloud Insights reports.

. In the left navigation pane, click *Team Content* and select the information category that you want to use.
. Click *Reports* to access the pre-defined reports.
. Click *Get Started*, *Samples*, or *Tutorials* to learn how to create reports.

image:Reporting-TeamContent/png[Team Content]
