---
sidebar: sidebar
permalink: concept_insights.html
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full,
summary: Insights give you a look into resource usage and trending.
---

= Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Insights allow you to look into things like resource usage and how it affects otehr resources, or time-to-full analysis.

== Insight Types

=== Shared Resources Under Stress

High-impact workloads can reduce the performance of other workloads in a shared resource. This puts the shared resource under stress. Cloud Insights provides tools to help you investigate resource saturation and impact in your environment. link:insights_shared_resources_under_stress.html[Learn More]

Note: The _Shared Resources Under Stress_ Insight is a Preview feature and subject to change. 


=== Time to Full (TTF)

Cloud Insights can analyze usage and predict when certain resources will reach capacity. link:insights_time_to_full.html[Learn More]

Note: The _Time-To-Full_ Insight is a Preview feature and subject to change.

