---
sidebar: sidebar
permalink: concept_whats_new.html
summary: New features and functionlity in Cloud Insights.
keywords: features
---

= What's New with Cloud Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
NetApp is continually improving and enhancing its products and services. Here are some of the latest features and functionalities available with Cloud Insights.

=== *July 2019*

==== TV Mode and Dashboard Auto-Refresh

Cloud Insights introduces *link:concept_dashboard_features.html#auto-refresh-and-tv-mode[TV Mode]*, which gives you an uncluttered, *Auto-Refreshing* display for constant, near-real-time viewing of any dashboard or landing page. Data is automatically refreshed according to the dashboard time range selected.

|===
|If Your Dashboard Time Range is:|The Auto-Refresh Interval is:
||3 Hours|1 Minute
|24 Hours|5 Minutes
|3 days|10 Minutes
|7 days|1 Hour 
|30 days|1 Hour 
|===


=== *June 2019*

==== Cloud Insights Editions

Cloud Insights is available in different Editions to fit your budget and business needs. Existing NetApp customers with an active NetApp support account can enjoy 7 days of data retention and access to NetApp data collectors with the free *Basic Edition*, or get increased data retention, access to all supported data collectors, expert technical support and more with *Standard Edition*. For more information on available features, see NetApp's link:https://cloud.netapp.com/cloud-insights[Cloud Insights] site.

==== New Infrastructure Data Collector: NetApp HCI

* link:task_dc_na_hci.html[NetApp HCI Virtual Center] has been added as an Infrastructure data collector. The HCI Virtual Center data collector collects NetApp HCI Host information and requires read-only privileges on all objects within the Virtual Center.

Note that the HCI data collector acquires from the HCI Virtual Center only. To collect data from the storage system, you must also configure the NetApp link:task_dc_na_solidfire[SolidFire] data collector.


=== *May 2019*

==== New Service Data Collector: Kapacitor

* link:task_config_telegraf_kapacitor.html[Kapacitor] has been added as a data collector for services.

==== Integration with Services via Telegraf

In addition to acquisition of data from infrastructure devices such as switches and storage, Cloud Insights now collects data from a variety of Operating Systems and Services, using link:task_config_telegraf_agent.html[Telegraf as its agent] for collection of integration data. Telegraf is a plugin-driven agent that can be used to collect and report metrics. Input plugins are used to collect the desired information into the agent by accessing the system/OS directly, by calling third-party APIs, or by listening to configured streams. 

Documentation for currently supported integrations can be found in the menu to the left under *Services Data Collector Reference*.


==== Storage Virtual Machine Assets 

* Storage Virtual Machines (SVMs) are available as assets in Cloud Insights. SVMs have their own Asset Landing Pages, and can be displayed and used in searches, queries, and filters. SVMs can also be used in dashboard widgets as well as associated with annotations.

==== Reduced Acquisition Unit System Requirements

* The system CPU and memory requirements for the Acquisition Unit (AU) software have been reduced. The new requirements are:

|===
|*Component*|*Old Requirement*|*New Requirement*
|CPU Cores|4|2
|Memory|16 GB|8 GB
|===

==== Additional Platforms Supported

* The following platforms have been added to those currently link:https://docs.netapp.com/us-en/cloudinsights/concept_acquisition_unit_requirements.html[supported for Cloud Insights]:

|===
|Linux|Windows
|CentOS 7.3 64-bit
CentOS 7.4 64-bit
CentOS 7.6 64-bit
Debian 9 64-bit
Red Hat Enterprise Linux  7.3 64-bit
Red Hat Enterprise Linux  7.4 64-bit
Red Hat Enterprise Linux  7.6 64-bit
Ubuntu Server 18.04 LTS
|Microsoft Windows 10 64-bit
Microsoft Windows Server 2008 R2
Microsoft Windows Server 2019
|===


=== *April 2019*

==== Filter Virtual Machines by Tags

When configuring the following data collectors, you can filter to include or exclude virtual machines from data collection according to their Tags or Labels. 

* link:task_dc_amazon_ec2.html#advanced-configuration[Amazon EC2]
* link:task_dc_ms_azure.html#advanced-configuration[Azure]
* link:task_dc_google_cloud.html#advanced_configuration[Google Cloud Platform]

=== *March 2019*

==== Email Notifications for Subscription-related Events

* You can select recipients for email link:concept_notifications_email.html[notifications] when subscription-related events occur, such as upcoming trial expiration or subscribed account changes. You can choose recipients for these notifications from among following:

** All Account Owners
** All Administrators
** Additional Email Addresses that you specify

==== Additional Dashboards

* The following new AWS-focused link:concept_import_from_dashboard_gallery.html[dashboards] have been added to the gallery and are available for import:
 ** AWS Admin - Which EC2 are in high demand?
 **	AWS EC2 Instance Performance by Region 


=== *February 2019*

==== Collecting from AWS Child Accounts

* Cloud Insights supports link:task_dc_amazon_ec2.html#collecting_from_aws_child_accounts[collection from AWS child accounts] within a single data collector. Your AWS environment must be configured to allow Cloud Insights to collect from child accounts.

==== Data Collector Naming 

* Data Collector names can now include periods (.), hyphens (-), and spaces ( ) in addition to letters, numbers, and underscores. Names may not begin or end with a space, period, or hyphen.


==== Acquisition Unit for Windows

* You can configure a Cloud Insights Acquisition Unit on a Windows server/VM. Review the Windows link:concept_acquisition_unit_requirements.html[pre-requisites] before installing the link:task_configure_acquisition_unit.html[Acquisition Unit software].


=== *January 2019*

==== "Owner" field is more readable

* In Dashboard and Query lists, the data for the "Owner" field was previously an authorization ID string, instead of a user-friendly owner name. The "Owner" field now shows a simpler and more readable owner name.

==== Managed Unit Breakdown on Subscription Page

* For each data collector listed on the *Admin > Subscription* page, you can now see a breakdown of Managed Unit (MU) counts for hosts and storage, as well as the total.


=== *December 2018*

==== Improvement of UI Load Time

* The initial loading time for the Cloud Insights user interface (UI) has been significantly improved. Refresh time for the UI also benefits from this improvement in circumstances where metadata is loaded.

==== Bulk Edit Data Collectors

* You can edit information for multiple data collectors at the same time. On the *Admin > Data Collectors* page, select the data collectors to modify by checking the box to the left of each and click the *Bulk Actions* button. Choose *Edit* and modify the necessary fields.
+
The data collectors selected must be the same vendor and model, and reside on the same Acquisition Unit.

==== Support and Subscription pages are Available During Onboarding

* During the onboarding workflow, you can navigate to the *Help > Support* and *Admin > Subscription* pages. Returning from those pages returns you to the onboarding workflow, providing you have not closed the browser tab.

=== *November 2018*

==== Subscribe through NetApp Sales or AWS Marketplace

* Cloud Insights subscription and billing is now available directly through NetApp. This is in addition to the self-serve subscription available through AWS Marketplace. A new *Contact Sales* link is presented on the *Admin > Subscription* page. For customers whose environments have or are expected to have 1,000 or more Managed Units (MUs), it is recommended to contact NetApp sales via the Contact Sales link.

==== Text Annotation Hyperlinks

* Text-type annotations can now include hyperlinks. 

==== Onboarding Walkthrough

* Cloud Insights now features an onboarding walkthrough for the first user (administrator or account owner) to log in to a new environment. The walkthrough takes you through installing an Acquisition Unit, configuring an initial data collector, and selecting one or more useful dashboards.

==== Import Dashboards from the Gallery

* In addition to selecting dashboards during onboarding, you can import dashboards via *Dashboards > Show All Dashboards* and clicking *+From Gallery*.

==== Duplicating Dashboards

* The ability to duplicate a dashboard has been added to the dashboard list page as a choice in the options menu for each dashboard, and on a dashboard's main page itself from the _Save_ menu.

==== Cloud Central products menu

* The menu allowing you to switch to other NetApp Cloud Central products has moved to the upper right corner of the screen.





