---
sidebar: sidebar
permalink: concept_cs_agent_requirements.html
summary: The server or VM you use as your Agent must meet minimum requirements
keywords: agent, Linux, requirements, docker, browsers, permissions, Network
---

= Agent Requirements 

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You must link:task_cs_add_agent.html[install an Agent] in order to acquire information from your data collectors. Before you install the Agent, you should ensure that your environment meets operating system, CPU, memory, and disk space requirements.

[cols=2*,options="header",cols="36,60"]
|===
|Component|Linux Requirement
|Operating system|A computer running a licensed version of one of the following:

Red Hat Enterprise Linux 7.2 64-bit
Red Hat Enterprise Linux 7.2 64-bit KVM
Red Hat Enterprise Linux 7.5 64-bit
Red Hat Enterprise Linux 7.5 64-bit KVM
Red Hat Enterprise Linux 7.8 64-bit
Red Hat Enterprise Linux 7.8 64-bit KVM
CentOS 7.2 64-bit
CentOS 7.2 64-bit KVM
CentOS 7.5 64-bit
CentOS 7.5 64-bit KVM
CentOS 7.8 64-bit
CentOS 7.8 64-bit KVM

This computer should be running no other application-level software. A dedicated server is recommended.
|Commands|The 'sudo su –' command is required for installation, running scripts, and uninstall.

//|Docker | The Docker CE package must be installed on the VM hosting the agent. 
//The agent systems should always have the Docker CE package installed. Users should not install the Docker-client-xx or Docker-common-xx native RHEL Docker packages since these do not support the 'docker run' CLI format that Cloud Secure supports. 
//|Java |OpenJDK Java is required. 
|CPU	|2 CPU cores 
|Memory	|16 GB RAM 
|Available disk space	|Disk space should be allocated in this manner:
//50 GB available for the root partition
/opt/netapp 25 GB
|Network|100 Mbps to 1 Gbps Ethernet connection, static IP address, IP connectivity to all devices, and a required port to the Cloud Secure instance (80 or 443).

|===

Please note: Cloud Insights agent and Cloud Secure agent can be installed in the same machine. However, it is a best practice to install them in separate machines. In the event that both agents are installed on the same machine, please allocate disk space as shown below:
+
|===
|Available disk space	|50 GB
For Linux, disk space should be allocated in this manner:
/opt/netapp 25 GB
/var/log/netapp 25 GB
|===

//// 

Removed from Table:

|Agent outbound URLs (port 433)|

\https://<site_name>.cs01.cloudinsights.netapp.com 
//You can get the site ID from the product URL. For example: https://*ab1234*.cs01.cloudinsights.netapp.com
You can use a broader range to specify the tenant ID: \https://*.cs01.cloudinsights.netapp.com/

\https://gateway.c01.cloudinsights.netapp.com 

\https://agentlogin.cs01.cloudinsights.netapp.com 

////



== Cloud Network Access Rules

[cols=5*,options="header"]
|===
|Protocol|Port|	Destination	|Direction|	Description
|TCP|443|<site_name>.cs01.cloudinsights.netapp.com 
<site_name>.c01.cloudinsights.netapp.com 
<site_name>.c02.cloudinsights.netapp.com|Outbound|Access to Cloud Insights
|TCP|443|gateway.c01.cloudinsights.netapp.com
agentlogin.cs01.cloudinsights.netapp.com|Outbound|Access to authentication services
|===

== In-network rules

[cols=5*,options="header"]
|===
|Protocol|Port|	Destination	|Direction|	Description
|TCP|389(LDAP)
636 (LDAPs / start-tls) |LDAP Server URL|Outbound|Connect to LDAP
|TCP|443|SVM Management IP Address|Outbound|API communication with ONTAP
|TCP|35000 - 55000|SVM data LIF IP Addresses|Inbound/Outbound|Communication with ONTAP for Fpolicy events
|===

//link:task_cs_add_agent.html[Configure an Agent]

// Supported browsers a
// * Internet Explorer 11 
// * Firefox ESR 60 
// * Chrome latest nightly (73.0)6
