---
sidebar: sidebar
permalink: concept_anomaly_detection.html
keywords: Active IQ, risks, svm, AIQ, risk
summary: Cloud Insights collects Risk data from NetApp Active IQ
---
= Anomaly Detection
:toc: macro
:hardbreaks:
:nofooter:
:toclevels: 1
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Anomaly Detection provides insight into variations to the "usual" patterns of data in your environment. An anomaly is a variation in a metric value for an object or group of objects, compared to historical information week over week. For example, if a pod's CPU utilization was at ~50% on Tuesday at 12:05 PM in previous weeks, but is at 100% this Tuesday at 12:05 PM, that would be considered an anomaly.

== A brief explanation of how Cloud Insights does this

It is not necessary to understand the "gears and pulleys" behind how Cloud Insights determines whether a data set is an anomaly or within "normal" range", but at a very high level: an anomaly occurs when a mean value of a metric is a number of standard deviations away from the mean of that metric for the previous week. Cloud Insights provides the ability to monitor data and gives you a choice of whether to alert on detected patterns that are more likely (i.e. fewer standard deviations away from normal), or less likely (more standard deviations away) to be determined to be an anomaly. 

