---
sidebar: sidebar
permalink: concept_import_from_dashboard_gallery.html
summary: You can import recommended dashboards to assist with answering business insight questions.
keywords: dashboard, gallery, import
---

= Importing from the Dashboard Gallery
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Data Infrastructure Insights provides a number of Recommended Dashboards to provide business insights into your data. Each dashboard contains widgets designed to help answer a particular question or solve a particular problem relevant to the data currently being collected on your tenant.

To import a dashboard from the gallery, do the following:

. Select *Dashboards > Dashboards*

. Click on *+From Gallery*
+
A list of *Recommended Dashboards* is displayed. Each dashboard is named with a particular question the dashboard can help you solve. Dashboards are available to help answer questions around different types of objects, including AWS, NetApp, Storage, VMware, and others

. Select one or more dashboards from the list and click *Add Dashboards*. These dashboards now show in your dashboard list.

In addition to the Recommended Dashboards, you can also choose to import *Additional Dashboards* that are not relevant to your current data. For example, if you have no storage data collectors currently installed but are planning on configuring some in the future, you may still choose to import the storage-relevant dashboards. These dashboards will be available for display but may not show any relevant data until at least one storage data collector is configured.

Importing from the dashboard gallery is available to users with Administrator or Account Owner role.
