---
sidebar: sidebar
permalink: cs_restrict_user_access.html
keywords: alert, snapshot,  attack
summary: With Cloud Secure, you can restrict user access in the event of suspected sabotage
---

= Restricting User Access

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media

[.lead]
Once a ransomware attack is detected, Cloud Secure can restrict user access from the machines being used to access the storage.

Restriction happens via IP address of the host machines, meaning the machines from which the user has accessed the storage. Those machine IP addresses will be blocked from accessing any of the Storage Virtual Machines (SVMs) monitored by Cloud Secure.

For example, let's say Cloud Secure manages 10 SVMs and the Automatic Response Policy is configured for four of those SVMs. If the attack originates in one of the four SVMs, the user's access will be restricted in all 10 SVMs. A Snapshot is still taken on the originating SVM.

If there are four SVMs with one SVM configured for CIFS, one configured for NFS, and the remaining two configured for both NFS and CIFS, all the SVMs will be blocked if the attack originates in any of the four SVMs.

=== Prerequisites for User Access Restriction

Customers must configure export policies for SMB and NFS for this feature to work. Follow the steps below if NFS and SMB are configured in the Cloud Secure Data Collector.
For both NFS and SMB, _csroles_ must be configured correctly. Customers should configure _csrole_ (if not configured already) when setting up an ONTAP SVM Data Source Collector as documented in the link:task_add_collector_svm.html#a-note-about-permissions[data collector permissions] documentation. 

If Cluster IP is used to configure the Data Collector then do the following from the ONTAP command line:

 security login role create -role csrole -cmddirname "vserver export-policy rule" -access all

If Server IP is used to configure the Data Collector then do the following from the ONTAP command line, inserting the correct _<vservername>_.

 security login role create -vserver <vservername> -role csrole -cmddirname "vserver export-policy rule" -access all

By default, there is an export policy created when the NFS service is created in the SVM. 

For SMB, then the export policies must be manually configured. Below are the commands to configure export policy. Copy the commands below to a text editor and replace the <vserver> name with the name of your vserver. Then copy each line one at a time and execute it in the ONTAP console. NOTE: you must first switch to advanced mode before pasting hte commands. 

TIP: This is particularly helpful for running PoCs. In the machines where you want to test, SMB can be configured as shown below. During PoCs, in the Data Source Collectors, enable only SMB/CIFs protocol and disable NFS protocol.

 set -privilege advanced
 cifs options modify -is-exportpolicy-enabled true -vserver <vserver>
 export-policy rule create -vserver <vserver> -policyname default -protocol cifs -clientmatch 0.0.0.0/0 -rorule any -rwrule any 

To Check if the _exportpolicy_ and _exportpolicy rule_ have been configured correctly, run the following commands after running the above commands.

 cifs options show  -fields is-exportpolicy-enabled -vserver <vserver>
 export-policy show -vserver <vserver>
 export-policy rule show -policyname default -vserver <vserver>

=== How to enable the feature?

* In Cloud Secure, navigate to *Admin > Automated Response Policies > Response Policy Settings > Access Limitation*.
* Set “Enable Restrict User Access” to _enabled_.

=== How to set up Automatic user blocking?

* Create a new Attack Policy or edit an existing Attack policy.
* Select the SVMs on which the attack policy should be monitored.
* Click on the checkbox “Restrict User IP File Access”. The feature will be enabled when this is selected.
* Under “Limit User Access” select what mode of restriction should be applied.
* Under “Time Period” select the time until which the restriction should be applied.

=== How to know if a user has been blocked because of an alert?

* In the alert lists page, a banner on the top of screen will be displayed in case any user is restricted.
* Clicking on the banner will take you to the “Users” page. In that the list of restricted users can be seen.
* In the “Users” page, there in a column named “IP Access”. In that column, the current state of user restriction will be displayed.

=== Can a user be manually restricted or un-restricted?

* You can simulate an attack via a link:concept_cs_attack_simulator.html[simulated script].
* You can go to the alert details or user details screen and then manually restrict or un-restrict a user from those screens.

=== What other details can be seen?

In the alert details page, you can view the access limitation history (i.e. when the user was restricted or un-restricted).

== Troubleshooting

|===
|Problem|Try This|

|Some of the users are not getting restricted, though there is an attack.	
|1.	Make sure that the Data Collector and Agent for the SVMs are in _Running_ state. Cloud Secure won’t be able to send commands if the Data Collector and Agent are stopped.

2. This is because the user may have accessed the storage from a machine with a new IP which has not been used before.
Restricting happens via IP address of the host through which the user is accessing the storage. Check in the UI (Alert Details > Access Limitation History for This User > Affected IPs) for the list of IP addresses which are restricted. If the user is accessing storage from a host which has an IP different from the restricted IPs, then the user will still be able to access the storage through the non-restricted IP. If the user is trying to access from the hosts whose IPs are restricted, then the storage won’t be accessible.

|Manually clicking on Restrict Access gives “No user IPs for the action”.	 
|The IP to be restricted is already being restricted from another user.

|Restrict Access fails with warning “Export policy usage for SMB protocol is disabled for the SVM. Enable use of export-policy to use restrict user access feature”	
|Ensure -is-exportpolicy-enabled option is true for the vserver as mentioned in the Prerequisites.

|===


