---
sidebar: sidebar
permalink: forensic_activity_history.html
keywords: Forensic, activity history, activity data, history  
summary: forensic activity history data 
---

= Forensic Activity History

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The Activity History page helps you understand the actions performed on entities in the Cloud Secure environment. 


== Examining Activity History Data  

Click *Forensic > Activity History* to access the Activity History page. The data available on this page describes:

* The time an entity was accessed including the year, month, day, and time of the last access. 

* The user that accessed the entity with a link to the link:forensic_user_detail.html[User Details].

//Above should be new user profile?

* The activity the user performed:  
** Create 
** Read
** Read Metadata
** Copy
** Delete
** Write

* The path to the entity with a link to the link:forensic_entity_detail.html[Entity Detail Data]
 
* The entity type:
** Stream
** File
** Directory
** Symbolic Link
** Other Type

* The location (IP address) from which the activity was performed. 


== Filtering Forensic Activity History Data

You can filter Forensic Activity History data by the following:


* The Activity type: 
** Created
** Read
** Read Metadata
** Copied
** Deleted
** Write
* Entity type: 
** Stream
** File
** Directory
** Symbolic Link
** Other Type
* Location that the entity was accessed from
* Path of the entity 
* Time the activity occurred
* User performing the activity

== Exporting Activity History

You can export the activity history to a .CSV file by clicking the _Export_ button above the Activity History table. Note that only the top 10,000 records are exported.



