---
sidebar: sidebar
permalink: forensic_community_overview.html
keywords:  Forensic, community, community detail, overview 
summary: forensic community detail
---

= Forensic Community Detail

[.lead]

Use the Forensic Community Page to understand the characteristics of communities that have been created in the Cloud Secure environment. 

== Community Profile 

Use the Community Profile information to understand:


* Entity profile

** Name
** Type
** Most accessed location
** Owner
** Size
** Path

== User and community

The user and community shows the number of times an entity has been accessed and from which communities access is being made. This section shows the following information:

* User and Community
** Users that accessed the entity
** Communities that accessed the entity
 
== Entity Behaviour

Entity behaviour identifies access information for the entity and details of operations performed on the entity. 

* Recent activity 
** Last accessed 
** Last accessed by 
** Last access location

* Operations performed on the entity
** Writes : 2
** Read : 0
** Accessed Meta Data : 0


