---
sidebar: sidebar
permalink: forensic_user_overview.html
keywords:  Forensic, user, user, activity 
summary: forensic user detail
---

= Forensic User Overview

[lead]
Information for each user is provided in the User Overview. Use these views to understand user characteristics, communities and entities the user is associated with, and the user's recent activities.   

== User Profile

User Profile information includes contact information and location of the user. The profile provides the following information:

* Name of the user
* Email address of the user
* User's Manager 
* Phone contact for the user
* Location of the user

== Communities and Entities

The communities and entities information identifies the following:

* The number of communities the user is associated with
* Total users in the associated communities
* Total entities in the associated communities

== User Behavior 

The user behavior information identifies recent activities and operations performed by the user. This information includes: 

* Recent activity
** Access location 
** Entities accessed 

* Operations for the last seven days
** Number of write operations 
** Number of read operations
** Number of times meta data was accessed  



