---
sidebar: sidebar
permalink: forensic_user_overview.html
keywords:  Forensic, user, user, activity 
summary: forensic user detail
---

= Forensic User Overview

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
Information for each user is provided in the User Overview. Use these views to understand user characteristics, associated entities, and recent activities.   

== User Profile

User Profile information includes contact information and location of the user. The profile provides the following information:

* Name of the user
* Email address of the user
* User's Manager 
* Phone contact for the user
* Location of the user


== User Behavior 

The user behavior information identifies recent activities and operations performed by the user. This information includes: 

* Recent activity
** Last access location 
** Activity graph
** Alerts

//** Entities accessed 

* Operations for the last seven days
** Number of operations 

//** Number of read operations
//** Number of times meta data was accessed  

== Refresh Interval
The User list is refreshed every 12 hours.

== Retention Policy
If not refreshed again, the User list is retained for 13 months. After 13 months, the data will be deleted.
If your Cloud Secure environment is deleted, all data associated with the environment is deleted.

