---
sidebar: sidebar
permalink: front_page_concept_2.html
summary: Welcome to the documentation portal for Cloud Insights.
---

= Cloud Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help

[blue][big]##*Front Page Concept #2*##

[.lead]
Cloud Insights provides intelligent operations and business insight across the enterprise, enabling the rationalization and optimization of costs, risk reduction, and advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage. 

IMPORTANT: This documentation is Preview documentation only. Topics and instructions are subject to change. For more information on Cloud Insights, go to http://cloud.netapp.com.

== What do you want to know?

|===
| *GETTING STARTED* | *MANAGING* | *HOW DO I...?* | *TROUBLESHOOTING*
| link:task_cloud_insights_onboarding_1.html[Onboarding] | link:concept_dashboards_overview.html[Using Dashboards] | link:task_io_density_report_no_root.html[Ensure IO Density Describes Internal Volumes Only] | TBD
| link:task_getting_started_with_cloud_insights.html[Collecting Data] |  link:concept_querying_assets.html[Querying Assets] | TBD | TBD
| link:concept_user_roles.html[Inviting Users] | link:task_defining_annotations.html[Using Annotations] | TBD | TBD
|  |  |  |


