---
sidebar: sidebar
permalink: task_getting_started_with_cloud_secure.html
summary: Getting started with Cloud Secure.
keywords: invite, roles, data collector, agent
---

= Getting started with Cloud Secure

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

After you have signed up for Cloud Secure and log in to your environment for the first time, there are configuration steps that need to be completed before you can begin collecting and analyzing data access information.  

//== See How It Works

//The first thing you see after logging in the first time is a short video explaining how Cloud Insights collects data. 

//When you are finished watching the video, click *Continue* to proceed to the next step.

== Install an Agent

An Agent is required to collect data for analysis by Cloud Secure. You install the Agent software on a server or VM in your environment. A single Agent can be used for multiple data collectors.

* See link:concept_cs_agent_requirements.html[Agent Requirements] and  link:task_cs_add_agent.html[Agent Installation] to install your Agent. 

== Configure Data Collectors

Cloud Secure collects data from from a User Directory collectors for user information and collects data from storage systems. Cloud Secure uses the data to analyze  user access to entities in the storage systems.

* To configure a User Directory Connector see,  link:task_config_user_dir_connect.html[User Directory Collector Configuration]

* To configure a Data Collector see the documentation in the menu to the left for each specific Data Collector. 


////
== Adding data collectors

Data collectors discover information from your data sources, such as storage devices, network switches, and virtual machines. The information gathered is used for analysis, validation, monitoring and troubleshooting. You need to link:task_configure_data_collectors.html[configure your data collectors] before Cloud Insights can gather data from them.

Related topics:
Data collector link:https://docs.netapp.com/us-en/cloudinsights/task_configure_data_collectors.html[*configuration*]
Vendor-specific link:concept_data_collector_reference.html[*Data Collector reference*]
Troubleshooting link:task_research_failed_collector.html[*Data Collector failures*] 
Data Collector link:reference_data_collector_support_matrix.html[*support matrix*]
////
