---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for Cloud Insights.
---

= Cloud Insights

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help

Cloud Insights provides intelligent operations and business insight across the enterprise, enabling the rationalization and optimization of costs, risk reduction, and advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage.

IMPORTANT: This documentation is Preview documentation only. Topics and instructions are subject to change. For more information on Cloud Insights, go to http://cloud.netapp.com.

link:task_cloud_insights_onboarding_1.html[Signing up for Cloud Insights]

link:task_getting_started_with_cloud_insights.html[Preparing to Collect Data]

link:concept_dashboards_overview.html[Using my Data: Working with Dashboards]

link:task_create_annotation.html[Using my Data: Annotating Assets]

Additional topics coming soon:

* Using my data:
** Querying
* Thresholds and Alerts
* How-To's
* FAQ
