---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for Cloud Insights.
---

= Cloud Insights
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help

Cloud Insights provides intelligent operations and business insights across the enterprise, enabling the rationalization and optimization of costs, risk reduction, and advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage.

toc::[]

== Setup and Collect data

. Deploy first preview build to preview cluster
. Create tenants for a small number of customers: (need info from whoever manages Auth0)
. Customer account owner invites user to visit the site (for preview we will send tenant link)
. Tenant owner / admin sets up AU for his server (using workarounds)
. Tenant owner / admin adds data collectors
. Tenant to troubleshoot data collector failures (data collector details page refactor, June)

== Find the Data You Want

. applies patch to fix data collector on behalf of DevOps (NetApp only)
. Customer searches assets and views data on landing page
. Customer builds dashboards
. Customer uses annotation and annotation rules to categorize data 

== Monitoring and Alerting

. Customer uses threshold to monitor performance:
. Customer creates performance policies (policy list / editor, June)
. Customer visits landing page to see violations in context (June)
. Customer does troubleshooting on expert view
