---
sidebar: sidebar
permalink: index.html
summary: Welcome to the documentation portal for Cloud Insights.
keywords: 
---

= Cloud Insights documentation
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help

[.lead]
NetApp Cloud Insights is a cloud infrastructure monitoring tool that gives you visibility into your complete infrastructure. With Cloud Insights, you can monitor, troubleshoot and optimize all your resources including your public clouds and your private data centers. 

//VIDEO HERE- TBD

//[big]##Cloud Insights provides intelligent operations and business insight across the enterprise, enabling the rationalization and optimization of costs, risk reduction, and advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage.##

== What can Cloud Insights do for me?

Cloud Insights provides hybrid multicloud monitoring, giving you full-stack observability of infrastructure and workloads.

* Data collectors for heterogeneous infrastructure and workloads, including Kubernetes
* Open Telegraf collector and open APIs for easy integration
* Comprehensive alerting and notifications
* Machine learning for intelligent insights
* Optimize resource utilization
* Built-in or customizable dashboards with advanced filters to minimize display noise to answer questions
* Discover the health of your ONTAP storage operations 
* Protect your most valuable business asset – data - from ransomware or data destruction attack


////
Cloud Insights helps you:

* *Reduce mean time to resolution by as much as 90%*
+
Stop log hunting for days and failing to manually correlate infrastructure: use our dynamic topology and correlation analysis to pinpoint the problem area immediately.

* *Reduce cloud infrastructure costs by an average of 33%*
+
Remove inefficiencies by identifying abandoned and unused resources and right-size workloads to their optimized performance and cost tiers.

* *Prevent as much as 80% of cloud issues from impacting end users*
+
End searching through vast amounts of data to find the relevant piece, by using advanced analytics and machine learning to identify issues before they become critical outages.
////

'''

== Getting Started

* How do I link:task_cloud_insights_onboarding_1.html[*get started*] with Cloud Insights?

* I'm signed up. Now what do I do? 
        link:task_getting_started_with_cloud_insights.html[Acquiring Data]
        link:concept_user_roles.html[Setting up users]
        
* Awesome! What's Next?
        link:task_defining_annotations.html[Preparing Assets: Annotating]
        link:concept_querying_assets.html[Finding the Assets You Want: Querying]
        link:concept_dashboards_overview.html[Seeing the Data You want: Dashboards]
        link:task_create_monitor.html[Monitoring and Alerts]
        link:task_cs_getting_started.html[Securing Data]
        
* This is great stuff! I'm ready to link:concept_subscribing_to_cloud_insights.html[*subscribe*].
        

        



