---
sidebar: sidebar
permalink: insights_overview.html
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace
summary: Insights give you a look into resource usage and trending.
---

= Insights
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Insights allow you to look into things like resource usage and how it affects other resources, or time-to-full analyses.

A number of Insights are available. Navigate to *Dashboards > Insights* to start diving in.  You can view active Insights (Insights that are currently occurring) on the main tab, or inactive Insights on the _Inactive Insights_ tab. Inactive Insights are those that were previously active but are no longer occurring.

== Insight Types

=== Shared Resources Under Stress

High-impact workloads can reduce the performance of other workloads in a shared resource. This puts the shared resource under stress. Data Infrastructure Insights provides tools to help you investigate resource saturation and impact on your tenant. link:insights_shared_resources_under_stress.html[Learn More]

//NOTE: This is a _Preview_ feature and may change over time as improvements are made. link:/concept_preview_features.html[Learn more] about Data Infrastructure Insights Preview features.


=== Kubernetes Namespaces Running Out of Space

The Kubernetes Namespaces Running Out of Space Insight gives you a view into workloads on your Kubernetes namespaces that are at risk of running out of space, with an estimate for the number of days remaining before each space becomes full. link:insights_k8s_namespaces_running_out_of_space.html[Learn More]

//NOTE: This is a _Preview_ feature and may change over time as improvements are made. link:/concept_preview_features.html[Learn more] about Data Infrastructure Insights Preview features.

=== Reclaim ONTAP Cold Storage

The _Reclaim ONTAP Cold Storage_ Insight provides data about cold capacity, potential cost/power savings and recommended action items for volumes on ONTAP systems. link:insights_reclaim_ontap_cold_storage.html[Learn More]

NOTE: This is a _Preview_ feature and may change over time as improvements are made. link:/concept_preview_features.html[Learn more] about Data Infrastructure Insights Preview features.

