---
permalink: legal-notices.html
sidebar: sidebar
keywords:
summary:
---

= Legal notices
:icons: font
:imagesdir: ../media/

// Include the common notices
include::https://raw.githubusercontent.com/NetAppDocs/common/main/_include/common-legal-notices.adoc[]

// Include the open source notice intro
include::https://raw.githubusercontent.com/NetAppDocs/common/main/_include/open-source-notice-intro.adoc[]

// Add required link(s)

[.lead]
Legal notices provide access to copyright statements, trademarks, patents, and more.

== Copyright

http://www.netapp.com/us/legal/copyright.aspx[^]

== Trademarks

NETAPP, the NETAPP logo, and the marks listed on the NetApp Trademarks page are trademarks of NetApp, Inc. Other company and product names may be trademarks of their respective owners.

http://www.netapp.com/us/legal/netapptmlist.aspx[^]

== Patents

A current list of NetApp owned patents can be found at:

https://www.netapp.com/us/media/patents-page.pdf[^]

== Privacy policy

https://www.netapp.com/us/legal/privacypolicy/index.aspx[^]


== Open source

Notice files provide information about third-party copyright and licenses used in NetApp software.

//* link:media/Notice_Cloud_Insights-2021.05.18.pdf[Notice for Cloud Insights]


link:media/Notice_Cloud_Insights-2023-04.pdf[Notice for Cloud Insights]
link:media/Notice_Cloud_Secure-2022-12-14.pdf[Notice for Workload Security (formerly Cloud Secure)]


