---
sidebar: sidebar
permalink: pre-requisites_for_k8s_operator.html
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s
summary: Cloud Insights supports Telegraf as its agent for collection of integration data on Kubernetes.  
---
= Before Installing or Upgrading the NetApp Kubernetes Monitoring Operator
:toc: macro
:hardbreaks:
:nofooter:
:toclevels: 2
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Read this information before installing or upgrading your NetApp Kubernetes Monitoring Operator.

Kubernetes Monitoring Operator installation is supported with Kubernetes version 1.20 or greater.

=== Pre-requisites:

//* If you are using a custom or private docker repository, follow the instructions in the Using a custom or private docker repository section
//* NetApp Kubernetes Monitoring Operator installation is supported with Kubernetes version 1.20 or greater.

//* When Cloud Insights is monitoring the backend storage and Kubernetes is used with the Docker container runtime, Cloud Insights can display pod-to-PV-to-storage mappings and metrics for NFS and iSCSI; other runtimes only show NFS.
//* Beginning August 2022, the NetApp Kubernetes Monitoring Operator includes support for Pod Security Policy (PSP). You must upgrade to the latest NetApp Kubernetes Monitoring Operator if your environment uses PSP.
//* If you are running on OpenShift 4.6 or higher, you must follow the OpenShift Instructions below in addition to ensuring these pre-requisites are met.
//* Monitoring is only installed on Linux nodes

////
Cloud Insights supports monitoring of Kubernetes nodes that are running Linux, by specifying a Kubernetes node selector that looks for the following Kubernetes labels on these platforms:

|===
|Platform	|Label
|Kubernetes v1.20 and above	|Kubernetes.io/os = linux
|Rancher + cattle.io as orchestration/Kubernetes platform	|cattle.io/os = linux
|===
////

//* The following commands must be available: curl, kubectl. The docker command is required for an optional installation step. For best results, add these commands to the PATH. Note that kubectl needs to be configured with access to the following kubernetes objects at a minimum: agents, clusterroles, clusterrolebindings, customresourcedefinitions, deployments, namespaces, roles, rolebindings, secrets, serviceaccounts, and services. See here for an example .yaml file with these minimum clusterrole privileges.
//* The host you will use for Operator installation must have kubectl configured to communicate with the target K8s cluster, and have Internet connectivity to your Cloud Insights environment.
//* If you are behind a proxy during installation, or when operating the K8s cluster to be monitored, follow the instructions in the link:task_config_telegraf_agent_k8s.html#configuring-proxy-support[Configuring Proxy Support] section of the Operator installation.
//* The NetApp Kubernetes Monitoring Operator installs its own kube-state-metrics to avoid conflict with any other instances.
// For accurate audit and data reporting, it is strongly recommended to synchronize the time on the Agent machine using Network Time Protocol (NTP) or Simple Network Time Protocol (SNTP).
//* If you are re-deploying the Operator (i.e. you are updating or replacing it), there is no need to create a _new_ API token; you can re-use the previous token.
//* Also note that if you have a recent NetApp Kubernetes Monitoring Operator installed and are using an API access token that is renewable, expiring tokens will automatically be replaced by new/refreshed API access tokens.
//* Network monitoring:  


|===
|Component|Requirement

|Platform
|The following platforms are supported:

   AWS Elastic Kubernetes Service (EKS)
   Azure Kubernetes Service (AKS)
   Google Kubernetes Engine (GKE)
   Red Hat OpenShift
   Rancher Kubernetes Engine (RKE)
   VMware Tanzu

Network monitoring must be running Linux kernel version 4.18.0 or above. Photon OS is not supported.

The Operator and its dependencies (telegraf, kube-state-metrics, fluentbit, etc.) are not supported on nodes that are running with Arm64 architecture.

|Labels
|Cloud Insights supports monitoring of Kubernetes nodes that are running Linux, by specifying a Kubernetes node selector that looks for the following Kubernetes labels on these platforms:

Kubernetes v1.20 and above: Kubernetes.io/os = linux
Rancher + cattle.io as orchestration/Kubernetes platform: cattle.io/os = linux


|Commands
|The _curl_, _kubectl_ commands must be available; for best results, add these commands to the PATH. 

Note that _kubectl_ needs to be configured with access to these kubernetes objects: 
agents
clusterroles
clusterrolebindings
customresourcedefinitions
deployments
namespaces
roles
rolebindings
secrets
serviceaccounts
services

|Connectivity
|The host you will use for Operator installation must have kubectl configured to communicate with the target K8s cluster, and have Internet connectivity to your Cloud Insights environment.

If you are behind a proxy during installation, or when operating the K8s cluster to be monitored, follow the instructions in the link:task_config_telegraf_agent_k8s.html#configuring-proxy-support[Configuring Proxy Support] section of the Operator installation.

For accurate audit and data reporting, it is strongly recommended to synchronize the time on the Agent machine using Network Time Protocol (NTP) or Simple Network Time Protocol (SNTP).


|Other
|If you are running on OpenShift 4.6 or higher, you must follow the link:[OpenShift Instructions in addition to ensuring these pre-requisites are met.

|API Token
|If you are re-deploying the Operator (i.e. you are updating or replacing it), there is no need to create a _new_ API token; you can re-use the previous token.

Also note that if you have a recent NetApp Kubernetes Monitoring Operator installed and are using an API access token that is renewable, expiring tokens will automatically be replaced by new/refreshed API access tokens.

|===


=== Configuring the Operator

In newer versions of the operator, most commonly modified settings can be configured in the _AgentConfiguration_ custom resource. You can edit this resource before deploying the operator by editing the _operator-config.yaml_ file. This file includes commented out examples of some settings. See the list of link:telegraf_agent_k8s_config_options.html[available settings] for the most recent version of the operator.

You can also edit this resource after the operator has been deployed using the following command:

	kubectl -n netapp-monitoring edit AgentConfiguration

To determine if your deployed version of the operator supports AgentConfiguration, run the following command:

	kubectl get crd agentconfigurations.monitoring.netapp.com
 
If you see an “Error from server (NotFound)” message, your operator must be upgraded before you can use the AgentConfiguration.



////
== Important Things to Note Before You Start

If you are running with a <<configuring-proxy-support,proxy>>, have a <<using-a-custom-or-private-docker-repository,custom repository>>, or are using <<openshift-instructions,OpenShift>>, read the following sections carefully.

Also read about <<permissions,Permissions>>.

If you are upgrading from a previous installation, read the <<upgrading,Upgrading>> information.



=== Configuring Proxy Support

There are two places where you may use a proxy in your environment in order to install the NetApp Kubernetes Monitoring Operator. These may be the same or separate proxy systems:

* Proxy needed during execution of the installation code snippet (using "curl") to connect the system where the snippet is executed to your Cloud Insights environment
* Proxy needed by the target Kubernetes cluster to communicate with your Cloud Insights environment

If you use a proxy for either or both of these, to install the NetApp Kubernetes Operating Monitor you must first ensure that your proxy is configured to allow good communication to your Cloud Insights environment. For example, from the servers/VMs from which you wish to install the Operator, you need to be able to access Cloud Insights and be able to download binaries from Cloud Insights.

For the proxy used to install the NetApp Kubernetes Operating Monitor, before installing the Operator, set the _http_proxy/https_proxy_ environment variables. For some proxy environments, you may also need to set the _no_proxy environment_ variable.

To set the variable(s), perform the following steps on your system *before* installing the NetApp Kubernetes Monitoring Operator:

. Set the _https_proxy_ and/or _http_proxy_ environment variable(s) for the current user:
.. If the proxy being setup does not have Authentication (username/password), run the following command:
+
 export https_proxy=<proxy_server>:<proxy_port>
 
.. If the proxy being setup does have Authentication (username/password), run this command:
+
 export http_proxy=<proxy_username>:<proxy_password>@<proxy_server>:<proxy_port>



For the proxy used for your Kubernetes cluster to communicate with your Cloud Insights environment, install the NetApp Kubernetes Monitoring Operator after reading all of these instructions.

Configure the proxy section of AgentConfiguration in operator-config.yaml before deploying the NetApp Kubernetes Monitoring Operator. 

----
agent:
  ...
  proxy:
    server: <server for proxy>
    port: <port for proxy>
    username: <username for proxy>
    password: <password for proxy>
    
    # In the noproxy section, enter a comma-separated list of
    # IP addresses and/or resolvable hostnames that should bypass
    # the proxy
    noproxy: <comma separated list>

    isTelegrafProxyEnabled: true
    isFluentbitProxyEnabled: <true or false> # true if Events Log enabled
    isCollectorsProxyEnabled: <true or false> # true if Network Performance and Map enabled 
    isAuProxyEnabled: <true or false> # true if AU enabled
  ...
...
----



=== Using a custom or private docker repository

By default, the NetApp Kubernetes Monitoring Operator will pull container images from the Cloud Insights repository. If you have a Kubernetes cluster used as the target for monitoring, and that cluster is configured to only pull container images from a custom or private Docker repository or container registry, you must configure access to the containers needed by the NetApp Kubernetes Monitoring Operator.

Run the “Image Pull Snippet” from the NetApp Monitoring Operator install tile. This command will log into the Cloud Insights repository, pull all image dependencies for the operator, and log out of the Cloud Insights repository. When prompted, enter the provided repository temporary password. This command downloads all images used by the operator, including for optional features. See below for which features these images are used for.

Core Operator Functionality and Kubernetes Monitoring

* netapp-monitoring
* kube-rbac-proxy
* kube-state-metrics
* telegraf
* distroless-root-user

Events Log

* fluent-bit
* kubernetes-event-exporter

Network Performance and Map

* ci-net-observer

Push the operator docker image to your private/local/enterprise docker repository according to your corporate policies. Ensure that the image tags and directory paths to these images in your repository are consistent with those in the Cloud Insights repository.

Edit the monitoring-operator deployment in operator-deployment.yaml, and modify all image references to use your private Docker repository.

 image: <docker repo of the enterprise/corp docker repo>/kube-rbac-proxy:<kube-rbac-proxy version>
 image: <docker repo of the enterprise/corp docker repo>/netapp-monitoring:<version>

Edit the AgentConfiguration in operator-config.yaml to reflect the new docker repo location. Create a new imagePullSecret for your private repository, for more details see _https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/_

----
agent:
  ...
  # An optional docker registry where you want docker images to be pulled from as compared to CI's docker registry 
  # Please see documentation link here: https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent_k8s.html#using-a-custom-or-private-docker-repository
  dockerRepo: your.docker.repo/long/path/to/test
  # Optional: A docker image pull secret that maybe needed for your private docker registry
  dockerImagePullSecret: docker-secret-name  
----




=== OpenShift Instructions

If you are running on OpenShift 4.6 or higher, you must edit the AgentConfiguration in _operator-config.yaml_ to enable the _runPrivileged_ setting: 

 # Set runPrivileged to true SELinux is enabled on your kubernetes nodes
 runPrivileged: true

Openshift may implement an added level of security that may block access to some Kubernetes components.



=== Permissions

If the cluster you are monitoring contains Custom Resources which do not have a ClusterRole which link:https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles[aggregates to view], you will need to manually grant the operator access to these resources to monitor them with Event Logs.

//or Change Management.

1. Edit _operator-additional-permissions.yaml_ before installing, or after installing edit the resource _ClusterRole/<namespace>-additional-permissions_
2. Create a new rule for the desired apiGroups and resources with the verbs ["get", "watch", "list"]. See \https://kubernetes.io/docs/reference/access-authn-authz/rbac/ 
3. Apply your changes to the cluster 
////


=== Tolerations and Taints

The _netapp-ci-telegraf-ds_, _netapp-ci-fluent-bit-ds_, and _netapp-ci-net-observer-l4-ds_ DaemonSets must schedule a pod on every node in your cluster in order to correctly collect data on all nodes. The operator has been configured to tolerate some well known *taints*. If you have configured any custom taints on your nodes, thus preventing pods from running on every node, you can create a *toleration* for those taints link:telegraf_agent_k8s_config_options.html[in the _AgentConfiguration_]. If you have applied custom taints to all nodes in your cluster, you must also add the necessary tolerations to the operator deployment to allow the operator pod to be scheduled and executed.

Learn More about Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[Taints and Tolerations].

Return to the link:task_config_telegraf_agent_k8s.html[*NetApp Kubernetes Monitoring Operator Installation* page]

