---
sidebar: sidebar
permalink: reference_legal_notices.html
keywords: copyrights, notice, trademarks, patents, privacy, open source
summary: Legal notices provide access to copyright statements, trademarks, patents, and more.
---

= Legal notices
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Legal notices provide access to copyright statements, trademarks, patents, and more.

== Copyright

http://www.netapp.com/us/legal/copyright.aspx[^]

== Trademarks

NETAPP, the NETAPP logo, and the marks listed on the NetApp Trademarks page are trademarks of NetApp, Inc. Other company and product names may be trademarks of their respective owners.

http://www.netapp.com/us/legal/netapptmlist.aspx[^]

== Patents

A current list of NetApp owned patents can be found at:

https://www.netapp.com/us/media/patents-page.pdf[^]

== Privacy policy

https://www.netapp.com/us/legal/privacypolicy/index.aspx[^]

== Open source

Notice files provide information about third-party copyright and licenses used in NetApp software.

////
* link:media/notice_cloud_manager_3.9.pdf[Notice for Cloud Manager 3.9^]
* link:media/notice_cloud_backup_service.pdf[Notice for the Cloud Backup^]
* link:media/notice_single_file_restore.pdf[Notice for Single File Restore^]
* link:media/notice_global_file_cache.pdf[Notice for Global File Cache^]
* link:media/notice_cloud_sync.pdf[Notice for Cloud Sync^]
* link:media/notice_cloud_tiering.pdf[Notice for Cloud Tiering^]
* link:media/notice_cloud_compliance.pdf[Notice for Cloud Data Sense (Cloud Compliance)^]
* link:media/notice_application_templates.pdf[Notice for Application Templates^]
////

