---
sidebar: sidebar
permalink: reporting_user_roles.html
summary: What you can do with Cloud Insights Reporting depends on your user role.
keywords: reporting, cognos, data warehouse, dwh, users, roles, user roles
---

= Cloud Insights Reporting User Roles

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
If you have Cloud Insights Premium Edition with Reporting, every Cloud Insights user in your environment also has a login to the Reporting application (i.e. Cognos). Simply click the *Reports* link in the menu and you will automatically be logged in to Reporting. 

Your user role in Cloud Insights determines your Reporting user role:

|===
|Cloud Insights Role|Reporting Role|Reporting Permissions
|Guest|Consumer|Can view, schedule, and run reports and set personal preferences such as those for languages and time zones. Consumers cannot create reports or perform administrative tasks.
|User|Author|Can perform all Consumer functions as well as create and manage reports and dashboards.
|Administrator|Administrator|Can perform all Author functions as well as all administrative tasks such as import and export of report definitions, configuration of reports, configuration of data sources, and the shutdown and restart of reporting tasks.
|===



////
The Reporting roles available are:

* *Cloud Insights Consumers* can view, schedule, and run reports and set personal preferences such as those for languages and time zones.
+
Note: Consumers cannot create reports or perform administrative tasks.

* *Cloud Insights Authors* can perform all Consumer functions as well as create and manage reports and dashboards

* *Cloud Insights Administrators* can perform all Author functions as well as all administrative tasks such as import and export of report definitions, configuration of reports, configuration of data sources, and the shutdown and restart of reporting tasks.
////


The following table shows the functions available to each Reporting role.

|===
|Feature	|Consumer	|Author	|Administrator
|View reports in the Team Content tab	|Yes	|Yes	|Yes
|Run reports	|Yes	|Yes	|Yes	
|Schedule reports	|Yes |Yes	|Yes
|Upload external files	|No	|Yes	|Yes
|Create Jobs| No|Yes|Yes
|Create Users|No|No|Yes
|Create stories	|No	|Yes	|Yes
|Create reports	|No	|Yes	|Yes
|Create Packages and Data Modules	|No	|Yes|Yes
|Perform administrative tasks	|No	|No	|Yes
//|Number of users	Number of OnCommand Insight users	20	2	1	1
|===

== Setting Reporting (Cognos) email preferences

NOTE: If you change your user email preferences within Cloud Insights Reporting (i.e. the Cognos application), those preferences are active _only for the current session_. Logging out of Cognos and back in again will reset your email preferences.



