---
sidebar: sidebar
permalink: reporting_querying_odata.html
summary: Integration of Odata / Olingo libraries allows users to query the DWH DB directly, without going through the Cognos Reporting environment.
keywords: reporting, cognos, data warehouse, dwh
---

= Cloud Insights Reporting Overview

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
Integration of Apache's Odata / Olingo libraries allows users to query the Cloud Insights Data Warehouse (DWH) database directly, without going through the Cognos Reporting environment.

== What is Apache Olingo?

Apache Olingo is a Java library that implements the Open Data Protocol (OData). Integration of Odata Olingo libraries allows users to perform read-only queries of the Cloud Insights Data Warehouse (DWH) directly, without going through the Cognos Reporting environment.

Note that the exception to the read-only limitation the _dwh_custom_ schema that is used for secondary ETL (Extract, Transform, Load) can be written.
However, this schema is not populated by ETL, so none of the collected data is sent there directly.

The current release of Olingo supports access via REST clients. Future versions are expected to support tools such as Tableau.

== REST client setup for Synchronous Queries



* These slides use the FireFox REST client plugin, any REST client should work
* 2 Headers are required:
** Name “X-CloudInsights-ApiKey”
** Attribute Value “<apikey>”
* Here is an example apikey, yours will be specific to your tenant:
+
“eyJraWQiOiI5OTk5IiwidHlwIjoiSldUIiwiYWxnIjoiSFMzODQifQ.eyJjcmVhdG9yTG9naW4iOiJhdXRoMHw1YjBlZTI4YWIzNTJjNjE5M2FhZWM2YTQiLCJkaXNwbGF5TmFtZSI6Ik9kYX
RhLXRlc3QgKG9uIGJlaGFsZiBvZiBNaWNoYWVsIFJ5YW4pIiwicm9sZXMiOltdLCJpc3MiOiJvY2kiLCJuYW1lIjoiT2RhdGEtdGVzdCIsImFwaSI6InRydWUiLCJleHAiOjE2NTQxMDI0OT MsImxvZ2luIjoiYjM1ZGNmZWEtMzgzMi00YWI5LTkxZmMtZDJkODJlNDY0Y2E5IiwiaWF0IjoxNjIyNTY2NDkzLCJ0ZW5hbnQiOiJiYzgxMTk3OS02ZDliLTRlOGItOGQzNy05NDNlYmE1
M2QwYzMifQ.K2iY2niou_k6lMBg_a6Gugq9bYL1Q-JV_3IanXh4x_YCOiJNo9Q11fuNweXMPQr3”

* All requests will start with the url - https://<tenant>/rest/v1/dwh-management/odata


