---
sidebar: sidebar
permalink: task_dc_amazon_ec2.html
keywords: data collector, EC2, 
summary: Configuring Amazon EC2 data collector.
---

= Configuring the Amazon EC2 data collector


:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]

Cloud Insights uses the Amazon EC2 data collector to acquire inventory and performance data from EC2 instances. 


== Requirements

In order to collect data from Amazon EC2 devices, you must have the following information: 

* You must have the IAM Access Key ID 
* You must have the Secret Access Key for your Amazon EC2 cloud account
* Port 433 HTTPS
* EC2 Instances can be reported as a Virtual Machine, or (less naturally) a Host. EBS Volumes can be reported as both a VirtualDisk used by the VM, as well as a DataStore providing the Capacity for the VirtualDisk.

Access keys consist of an access key ID (for example, AKIAIOSFODNN7EXAMPLE) and a secret access key (for example, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY). You use access keys to sign programmatic requests that you make to EC@ if you use the Amanzon EC2 SDKs, REST, or Query API operations. These keys are provided with your contract from Amazon.   


== Configuration

Enter data into the data collector fields according to the table below:

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|AWS Region|Choose AWS region
|IAM Role|AWS IAM Role if running on EC2 instance to retrieve IAM temporary access key, secret and token. Required if you do not use IAM Access Key ID and Secret Access Key fields.
|AWS IAM Access Key ID|Enter AWS IAM Access Key ID. Required if you do not use IAM Role.
|AWS IAM Secret Access Key|Enter AWS IAM Secret Access Key. Required if you do not use IAM Role.
|I understand AWS bills me for API requests|Check this to verify your understanding that AWS bills you for API requests made by Cloud Insights polling.
|===

== Advanced Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Include Extra Regions| Specify additional regions to include in polling. 
|Cross Account Role|Role for accessing resources in different AWS accounts.
|Inventory Poll Interval (min)|The default is 60
|Choose 'Exclude' or 'Include' to Apply to Filter VMs by Tags|Specify whether to include or exclude VM's by Tags when collecting data. If ‘Include’ is selected, the Tag Key field can not be empty.
|Tag Keys and Values on which to Filter VMs|Click *+ Filter Tag* to choose which VMs (and associated disks) to include/exclude by filtering for keys and values that match keys and values of tags on the VM. Tag Key is required, Tag Value is optional. When Tag Value is empty, the VM is filtered as long as it matches the Tag Key.
//|HTTP connection and socket timeout (sec)|The default is 300
//|Include AWS tags|Check to enable support for AWS tags in Cloud Insights annotations.
|Performance Poll Interval (sec)|The default is 1800
|===

== Mapping Amazon tags to Cloud Insights annotations

The Amazon EC2 data collector includes an option that allows you to populate Cloud Insights annotations with tags configured on EC2. The annotations must be named exactly as the EC2 tags. Cloud Insights will always populate same-named text-type annotations, and will make a "best attempt" to populate annotations of other types (number, boolean, etc). If your annotation is of a different type and the data collector fails to populate it, it may be necessary to remove the annotation and re-create it as a text type.

Note that AWS is case-sensitive, while Cloud Insights is case-insensitive. So if you create an annotation named "OWNER" in Cloud Insights, and tags named "OWNER", "Owner", and "owner" in EC2, all of the EC2 variations of "owner" will map to Cloud Insight's "OWNER" annotation. 

.Related Information

* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Managing Access Keys for IAM Users^]

== Include Extra Regions

In the AWS Data Collector *Advanced Configuration* section, you can set the *Include extra regions* field to include additional regions, separated by comma or semi-colon. By default, this field is set to *_us-.*_*, which collects on all US AWS regions.  To collect on _all_ regions, set this field to  *_.*_*. 
If the *Include extra regions* field is empty, the data collector will collect on assets specified in the *AWS Region* field as specified in the *Configuration* section. 

== Collecting from AWS Child Accounts

Cloud Insights supports collection of child accounts for AWS within a single AWS data collector. Configuration for this collection is performed in the AWS environment:

* You must configure each child account to have an AWS Role that allows the master account ID to access EC2 details from the children account. 
* Each child account must have the role name configured as the same string. 
* Enter this role name string into the Cloud Insights AWS Data Collector *Advanced Configuration* section, in the *Cross account role* field.

Best Practice: It is highly recommended to assign the AWS predefined _AmazonEC2ReadOnlyAccess_ policy to the ECS master account. Also, the user configured in the data source should have at least the predefined _AWSOrganizationsReadOnlyAccess_ policy assigned, in order to query AWS. 


Please see the following for information on configuring your environment to allow Cloud Insights to collect from AWS child accounts:

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html[Tutorial: Delegate Access Across AWS Accounts Using IAM Roles]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html[AWS Setup: Providing Access to an IAM User in Another AWS Account That You Own]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html[Creating a Role to Delegate Permissions to an IAM User]

           
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].



