---
sidebar: sidebar
permalink: task_configure_data_collectors.html
keywords: acquisition, AU, data collector, collector
summary: A summary.
---

= Configuring Data Collectors

[.lead]
You configure Data Collectors in your Cloud Insights environment to collect data from devices in the data center.

.Before you begin

* You must have Account Owner or Admin privileges to configure data collectors. 
* You must have configured an Acquisition Unit before you can start collecting data.
* You need credentials for the devices from which you are collecting data.
+
Device network addresses, account information, and passwords are required for all devices you are collecting data from.

.Steps
. From the Cloud Insights menu, click *Admin > Data Collectors*
+
The system displays the Installed Data Collectors.

. To add a new data collector, click *Available Data Collectiors* on the required vendor.
+
In the dialog box you can configure the data collector and add an Acquisition Unit.
. Enter a unique name for the data collector.
+
Names can contain can contain letters (a-z), numbers (0-9), dashes (-), underscores (_), apostrophes ('), and periods (.).
. Enter the *Acquisition Unit* to associate with this data collector.
. Enter the required fields in the Configuration screen.
. Click *Advanced Configuration* to add additional configuration fields. (Not all data collectors require advanced configuration.)
. Click *Test Configuration* to verify that the data collector is properly configured.

For help adding a new Acquisition Unit, see link:task_configure_acquisition_unit.html[Configuring acquisition units]
