---
sidebar: sidebar
permalink: task_dc_vmware.html
keywords: data collector, VMware, 
summary: Configuring VMware  data collector.
---

= Configuring the VMware VSphere data collector 
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The data collector for VMware vSphere collects ESX Host information and requires read-only privileges on all objects within the Virtual Center. 

== Terminology

Cloud Insights acquires the following inventory information from the VMware vSphere data collector. For each asset type acquired, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|Virtual disk|Disk
|Host|Host
|Virtual machine|Virtual machine
|Data store|Data store
|LUN|Volume
|Fibre channel port|Port
|===
These are common terminology mappings only and might not represent every case for this data collector. 

== Requirements

The following information is required to configure this data collector:

* IP address of the Virtual Center server 
* Read-only username and password in Virtual Center 
* We require read only privileges on all objects within Virtual Center. 
* SDK access on the Virtual Center server – normally already setup. 
* Port requirements: http-80 https-443 
* Validate access: 
** Log into Virtual Center Client using above username and password 
** Verify SDK enabled: telnet <vc_ip> 443 

== Setup and connection

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Name|Unique name for the data collector
|Acquisition unit|Name of acquisition unit
|===

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Virtual center IP Address |IP address of the Virtual Center
|User name |User name used to access the Virtual Center 
|Password|Password used to access the Virtual Center 
|===

== Advanced configuration 

In the advanced configuration screen, check the *VM Performance* box to collect performance data. Inventory collection is enabled by default. 
The following fields can be configured:

[cols=2*,  cols"50,50"]
|===
|Field|Description
|Inventory poll interval (min)  | Default is 20
//|Connection Timeout (ms)|Default is 60000
|Filter VMs |Select CLUSTER, DATACENTER, or ESX HOST

//or you can choose to filter by TAG 

|Choose 'Exclude' or 'Include' to Specify a List|Create a filter list (CLUSTER, DATACENTER, and/or ESX_HOST) 
|Number of retries | Default is 3 
|Communication port| Default is 443 

//|Tag Keys and Values on which to Filter VMs|Click *+ Filter Tag* to choose which VMs (and associated disks) to include/exclude by filtering for keys and values that match keys and values of tags on the VM. Tag Key is required, Tag Value is optional. When Tag Value is empty, the VM is filtered as long as it matches the Tag Key.
//Tag filtering is only available in VSphere 6.0 Beta or later.

|Filter Device List...|This list must consist of exact string matches - if you intend to filter by ESX_HOST, you must build a comma delimited list of the exact "names" of your ESX hosts as reported in both Cloud Insights and vSphere. These "names" may be either IP addresses, simple hostnames, or fully qualified domain names (FQDNs) - this is determined by how these hosts were named when they were originally added to vSphere.

When filtering by CLUSTER, use the Cloud Insights-style cluster names as reported by CI on hypervisors - Cloud Insights prepends the vSphere cluster name with the vSphere datacenter name and a forward slash - "DC1/clusterA" is the cluster name Cloud Insights would report on a hypervisor in clusterA within data center DC1.

|Performance poll interval (sec)|Default is 300  
|===


== Mapping VMware tags to Cloud Insights annotations

The VMware data collector allows you to populate Cloud Insights annotations with tags configured on VMware. The annotations must be named exactly as the VMware tags. Cloud Insights will always populate same-named text-type annotations, and will make a "best attempt" to populate annotations of other types (number, boolean, etc). If your annotation is of a different type and the data collector fails to populate it, it may be necessary to remove the annotation and re-create it as a text type.

Note that VMware tags may be case-sensitive, while Cloud Insights tags are case-insensitive. So if you create an annotation named "OWNER" in Cloud Insights, and tags named "OWNER", "Owner", and "owner" in VMware, all of those variations of "owner" would map to Cloud Insight’s "OWNER" annotation.

Keep the following in mind:

* Cloud Insights currently only auto-publishes support information for NetApp devices.
* Since this support information is held in annotation form, you can query it or use it in dashboards. 
* If a user overwrites or empties the annotation value, the value is autofilled again when Cloud Insights updates annotations, which it does once a day.



== Troubleshooting
Some things to try if you encounter problems with this data collector:

=== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|Error: Include list to filter VMs cannot be empty
|If Include List is selected, please list valid DataCenter, Cluster, or Host names to filter VMs
|Error: Failed to instantiate a connection to VirtualCenter at IP
|Possible solutions:

* Verify credentials and IP address entered.
* Try to communicate with Virtual Center using VMware Infrastructure Client.
* Try to communicate with Virtual Center using Managed Object Browser (e.g MOB).
|Error: VirtualCenter at IP has non-conform certificate that JVM requires
|Possible solutions:

* Recommended: Re-generate certificate for Virtual Center by using stronger (e.g. 1024-bit) RSA key.
* Not Recommended: Modify the JVM java.security configuration to leverage the constraint jdk.certpath.disabledAlgorithms to allow 512-bit RSA key. See JDK 7 update 40 release notes at "http://www.oracle.com/technetwork/java/javase/7u40-relnotes-2004172.html"
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:reference_data_collector_support_matrix.html[Data Collector Support Matrix].



