---
sidebar: sidebar
permalink: security_overview.html
summary:  Cloud Insights follows security best practices throughout the release life cycle.
keywords: security, risk, protection
---

= Managing security on the acquisition unit

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The securityadmin tool allows you to manage security options on the acquisition user (AU). Security management includes managing keys and passwords, saving and restoring security configurations you create or restoring configurations to the default settings.

Before you begin

* You must have admin privileges on the AU server to perform security configuration tasks.

About this task

You use the securityadmin tool to manage security. The securityadmin tool is installed by default in the following locations on the AU server:

* Windows - _C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat_
* Linux - _/bin/oci-securityadmin.sh_

Procedure

Log in to the Cloud Insights Acquisition Unit server.

Start the security admin tool in interactive mode (-i).
The system requests login credentials.
Enter the user name and password for an account with Admin credentials.
Select Local Acquisition Unit to reconfigure the Local Acquisition Unit security configuration.
The following options are displayed:
Backup
Creates a backup zip file of the vault containing all passwords and keys and places the file in a location specified by the user, or in the following default locations:
Windows - C:\Program Files\SANscreen\backup\vault
Linux - /var/log/netapp/oci/backup/vault
Restore
Restores the zip backup of the vault that was created. Once restored, all passwords and keys are reverted to values existing at the time of the backup creation.
Note: Restore can be used to synchronize passwords and keys on multiple servers, for example:
Change encryption keys on the LAU
Create a backup of the vault
Restore the vault backup to each of the RAUs
Change Encryption Keys
Change the AU encryption keys used to encrypt or decrypt device passwords.
Important: When you change encryption keys, you should backup your new security configuration so that you can restore it after an upgrade or installation.
Update Password
Change password for 'acquisition' user account.
Important: Some accounts need to be synchronized when passwords are changed. For example, if you change the password for the 'acquisition' user on the server, you need to change the password for the 'acquisition' user on the LAU, RAU, DWH, and EMU to match. Also, when you change passwords, you should backup your new security configuration so that you can restore it after an upgrade or installation.
Reset to Defaults
Resets acquisition user password and acquisition user encryption keys to default values, Default values are those provided during installation.
Exit
Exit the securityadmin tool.
Chose the option you want configure and follow the prompts.

=== Special considerations for special characters

Due to the limitations of the windows installer, a proxy password with certain special characters cannot be configured during install time. If the proxy password cannot be configured directly (you will see a pop-up message) skip the proxy setup step. After installation, use the securityadmin tool (default location is <install drive>\Program Files\Cloud Insights\Acquisition Unit\acq\securityadmin\bin\securityadmin.bat) to configure the proxy.

Double quote(") is used to escape these special characters: <, >, ^, |, &, !. Thus, double quote cannot be used in password.

For example: if the password is P@'sswo!rd, run the following command to add the proxy configuration:

<install drive>\Program Files\Cloud Insights\Acquisition Unit\acq\securityadmin\bin\securityadmin.bat -pr -ap ip=<proxy IP> port=<proxy port> user=<proxy user> password=P@'sswo"^!rd

<, >, ^, |, & can be escaped by ".
For example: password is Pa^sswd, then the password can be entered as password=Pa"^sswd

! can be escaped by "^
For example: password is Passw!d, then the password can be entered as password=Passw"^!d

If the password contains more than one special characters, the double quote can only be used once and has to be used at where the first special character appears.
For example: password is Pa&ssw!d, then the password can be entered as password=Pa"&ssw^!d

If the password contains both ^ and !, then you need to use another ^ to escape itself.
For example: password is Pa^ssw!d, then the password can be entered as password=Pa"^^ssw^!d

