---
sidebar: sidebar
permalink: task_dc_ceph_storage.html
keywords: data collector, ceph
summary: Configuring ceph data collector.
---

= Ceph storage data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/



[.lead] 

Cloud Insights uses the Ceph storage data collector to discover inventory data from the Ceph storage  platform.

== Terminology

Cloud Insights acquires inventory information with the Ceph storage data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|Pool|Storage Pool
|FileSystem|Internal Volume
|OSD|Backend LUN
|===

Note: These are common terminology mappings only and might not represent every case for this data source.

== Requirements

* The Ceph administrator IP address 
* Administrator user name and password
* Port requirement: SSH Port 22

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Ceph admin IP address|Ip address for the for the Ceph storage
|User name|User name for the Ceph storage system administrator user account
|Password|Password for the administrator user account
|===

== Advanced configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Inventory poll interval (min)|Interval between inventory polls. The default is 60 minutes.
//|SSH process wait timeout (sec)|Connection timeout. The default is 60 seconds. 
|SSH port|The default is port 22. 
|===

           
== Troubleshooting
Some things to try if you encounter problems with this data collector:

==== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|Command missing
|Verify that the user has permissions to run the commands noted below on the device
* Verify that the ceph adminstration tools are installed, please run the following command: rpm -q ceph-common.x86_64
* Verify credentials used in the wizard match device credentials 
|Invalid configuration
|* Verify that the pools are configured in the system, try running the following command: ceph osd lspools -f json-pretty
* Verify credentials used in the wizard match device credentials
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].
