---
sidebar: sidebar
permalink: task_cloud_insights_onboarding_1.html
summary: Signing up for Cloud Insights and creating your environment.
---

= Cloud Insights Onboarding

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: Cloud Insights, documentation, help, onboarding, getting started, 

[.lead]
Before you can start working with Cloud Insights, you must sign up on the *NetApp Cloud Central* portal. If you already have a NetApp Cloud Central login, you can start a free trial of Cloud Insights with a few quick steps.

toc::[]

== Creating your NetApp Cloud Central account

To sign up for access to NetApp's cloud services, go to https://cloud.netapp.com[*NetApp Cloud Central*^] and click *Sign Up*.

* Enter a valid business email address and choose a password.
* Enter your company name, and your full name.
* Accept the terms and conditions and click *Sign Up*.

You will then be taken to NetApp's cloud offerings page.

Select Cloud Insights.

=== What if I already have a NetApp Cloud login?

If you already have a NetApp Cloud Central account, simply choose *Log In* on the https://cloud.netapp.com[*NetApp Cloud Central*^] portal page.

Enter your email address and password. You will then be taken to NetApp's cloud offerings page.

Select Cloud Insights.

== Starting your Cloud Insights free trial

If this is your first time logging in to Cloud Insights, under the Cloud Insights offering, click on *Start Free Trial*. Cloud Insights will then create your company's environment.

Once the creation of your environment is complete, you can use your Cloud Central credentials to log in and start your free, 30-day trial of Cloud Insights. During this trial you can explore all the features that Cloud Insights Standard Edition has to offer. 

During the free trial, you can link:concept_subscribing_to_cloud_insights.html[start your subscription] to Cloud Insights at any time. When you are subscribed, You can use the Cloud Insights features based on your current subscription.


== Sign in and go

Once your tenant has been created, at any time you can simply log in to the NetApp Cloud Portal and click *Go to Cloud Insights*. You will be taken directly to your Cloud Insights environment.

You can also open a browser directly to your Cloud Insights environment URL, for example:

 https://<environment-name>.c01.cloudinsights.netapp.com/

The URL will also be included in each user's invitation email for simple access and bookmarking. If the user is not already logged in to Cloud Central, they will be prompted to log in.

NOTE: New users must still sign up for access to Cloud Central before they can access their environment URL.

The first time you log in to a new environment, you will be guided through setting up to link:task_getting_started_with_cloud_insights.html[*begin gathering data*].

== Logging Out

To log out of Cloud Insights, click your *User Name* and select *Log Out*. You will be taken back to the Cloud Central sign in screen.

NOTE: Logging out of Cloud Insights logs you out of Cloud Central. You will also be logged out of other NetApp Cloud services that use the Cloud Central sign-in.
