---
sidebar: sidebar
permalink: task_dc_dell_compellent.html
keywords: data collector, Dell, compellent 
summary: Configuring Dell Compellemt data collector.
---

= Dell Compellent Storage Center data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead] 

Cloud Insights uses this data collector to discover inventory and performance information for the Dell Compellent Storage Center storage arrays. This data collector uses the Dell Java API.


== Terminology

Cloud Insights acquires the following inventory information from the Dell Compellent data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Disk|Disk
|Disk Folder|Disk Group
|Storage Center|Storage
|Controller|Storage Node
|Storage Type|Storage Pool
|Volume|Volume
|Fiber Channel I/O Port|Port
|===

Note: These are common terminology mappings only and might not represent every case for this data collector.

== Requirements
 
* Administrator credentials for the Dell Compellent Enterprise Manager server
* IP address of the Compellent Enterprise Manager server
* Port 3033 for access to the device

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Address of Enterprise Manager|IP address of the Compellent Enterprise Manager server
|Port|Port used for communication with of the Compellent Enterprise Manager server
|User Name|User name for the Compellent Enterprise Manager server 
|Password|Password used for the Compellent Enterprise Manager server
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Poll Interval (min)|Interval between inventory polls. The  default is 60 minutes. 
|Performance Poll Interval (up to 3600 seconds)|Interval between performance polls. The default is 300 seconds. 
|===

== Troubleshooting
Some things to try if you encounter problems with this data collector:

==== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|"Configuration error" with error message “Could not communicate with the device: Connection timed out.”
|* Check ip address
* Check User name and password
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].
