---
sidebar: sidebar
permalink: task_dc_na_astra_data_store.html
summary: Configure NetApp Astra Datastore
keywords: data collector, queries, create, astra, ads
---

= NetApp Astra Datastore data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The NetApp Astra Datastore datasource monitors and reports configuration and performance data for a single Astra Datastore (ADS) cluster. 

== Terminology

Cloud Insights acquires inventory and performance data from this collector. For each asset type acquired, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|AstraDSVolume|Internal Volume
|AstraDSNodeInfo.status.drives|Disk
|AstraDSNodeInfo|Storage Node
|AstraDSExportPolicy|Share / Share Initiator
|AstraDSCluster|Storage
|===


== Configuration
[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Kubernetes API IP Address|The IP address of the kubernetes API server
|Kubernetes API Port|The port of the kubernetes API server
|Kubernetes API Token|Base64 encoded Kubernetes API token
|Include Cluster Names|Comma separated list of cluster names to monitor. Empty = monitor all clusters
|===

== Advanced Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Inventory Poll Interval (min)|Interval between inventory polls. The default is 60 minutes.
|Performance Poll Interval (sec)|Interval between performance polls. The default is 300 seconds. 
|ADS Metrics Endpoint|ADS cluster Metrics endpoint (May not be needed)
|===

           
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].

