---
sidebar: sidebar
permalink: task_io_density_report_no_root.html
summary: When querying for high I/O density you want to exclude root volumes.
keywords: NetApp, root volume, high I/O,
---

= Ensuring IO density reports describe only internal data volumes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp root volume contains directories and configuration files for managing the storage system. When querying for high I/O density you want to exclude these root volumes.

When monitoring your environment it is more important to determine which internal data volumes are producing high I/O density numbers. In order to accurately identify only the data volumes, you need to isolate the NetApp internal volumes from queries you use to monitor I/O density.

This guide describes how to easily identify the NetApp root aggregates, isolate them from the results of internal volume queries, and create rules that exclude any new NetApp root aggregates as they are added to the system. The following Insight features are used to insure that your I/O density reports are derived from internal data volumes:

* A query is created to identify all of the NetApp root aggregates that are monitored by Insight.
* An annotation is assigned to each of the NetApp root aggregates.
* An annotation rule is created to apply the annotation to new NetApp root aggregates.

The steps in this guide can also be applied to other vendor's storage systems. You will need to identify the volumes that contain directories and configuration files for managing the storage system and use similar steps to exclude these volumes.

== Creating a query to identify NetApp root aggregates

Queries provide search at a granular level, based on user-selected criteria. Using a query allows you to search for Internal volumes on your tenant that contain the NetApp root aggregate.

.Steps

. Create a query to identify NetApp root aggregates on your tenant: Click *Queries > New Query > Select Resource Type* (?)
. Click *storage Pool*
. Enter the name for the root aggregate
+
This example uses "aggr0" for the name. When creating an aggregate, only the following requirements for the name must be followed:

.. It must begin with either a letter or an underscore (_).
.. It can contain only letters, digits, and underscores.
.. It can be 250 characters or less.
In most cases, the aggregate is name aggr0, aggr_0, or something similar. It might require an iterative process to identify all of the NetApp root aggregates on your tenant.
. Click *Save* and enter a name for the new query.
+
As mentioned before, this might be an iterative process and require multiple queries to identify all of the NetApp root aggregates.

== Create an annotation for the root volumes returned by your queries

Annotations are specialized notes that you assign to your assets, allowing you to filter assets by their annotations. The annotation you create will be used to identify the NetApp root aggregates on your tenant and ensure that they are not included in a specific report.

.Before you begin

You must have identified all of the root aggregates you want to exclude from the "High I/O Density" report.

.Steps

. In the Data Infrastructure Insights menu, click *Manage > Annotations*
. Click *Add*
.. Enter the name for the annotation: *RootAggr*
.. Enter a description of the annotation: *Remove root aggregate from "High I/O Density" report*
.. Enter the type of annotation: *Boolean*
. Click *Save*

== Create an annotation rule to automate excluding specific aggregates from your I/O density report

As an alternative to manually applying annotations to individual assets, you can automatically apply annotations to multiple assets using annotation rules. Annotation rules are based on queries you create and when run on the system they add new assets to existing sets of assets. When these sets of assets are excluded from a report the new assets are automatically excluded too.

.Before you begin
You must have created and saved a query that identifies the NetApp root aggregates you identified on your tenant.

.Steps

. In the Data Infrastructure Insights toolbar, Click *Manage > Annotation rules*.
. Click *Add*. The Add Rule dialog displays.

.. In the Name box, enter a unique name that describes the rule: *"RootAggrExclude"*
.. Click Query and select the Query that Insight should use to apply the annotation rule to: *"Aggregate0"*
.. Click Annotation and select: *"Root agg exclude"*
.. Click *Value* and enter *True*
