---
sidebar: sidebar
permalink: task_dc_emc_datadomain_configure.html
keywords: data collector, Data Domain, EMC, DELL
summary: Configuring DELL EMC Data Domain data collector.
---

= DELL EMC Data Domain data collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This data collector gathers storage and configuration information from Dell EMC Data Domain deduplication storage systems. To add the data collector, you must use specific configuration instructions and commands and be aware of data collector requirements and usage recommendations.

== Terminology

Cloud Insights acquires the following inventory information from the Data Domain data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|Disk|Disk
|Array|Storage
|Port|Port
|File System|Internal Volume
|Quota|Quot
|NFS and CIFS share|FileShare
|===

Note: These are common terminology mappings only and might not represent every case for this data source.

== Requirements

You need the following information to configure this data collector:

* Read-only user name and password to the Data Domain storage 
* Validated access by using _telnet_ to port 22

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|IP address|The IP address or fully-qualified domain name of the Data Domain storage array 
|User name|The user name for the Data Domain storage array
|Password|The password for the Data Domain storage array 
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|Inventory Poll Interval (min)|Interval between inventory polls. The default is 20 minutes. 
|SSH Process Wait Timeout (sec)|SSH process timeout. The default is 180 seconds.
|SSH Port|SSH service port 
