---
sidebar: sidebar
permalink: task_configure_data_collectors.html
keywords: acquisition, AU, data collector, collector
summary: General data collector instructions
---

= Configuring Data Collectors


[.lead]
You configure Data Collectors in your Cloud Insights environment to collect data from devices in the data center.

.Before you begin
* You must have configured an Acquisition Unit before you can start collecting data.
* You need credentials for the devices from which you are collecting Data.
* Device network addresses, account information, and passwords are required for all devices you are collecting data from.

.Steps
. From the Cloud Insights menu, click *Admin > Data Collectors*
+
The system displays the available Data Collectors arranged by vendor.
. Click *+ Collector* on the required vendor and select the data collector to configure.
+
In the dialog box you can configure the data collector and add an Acquisition Unit.
. Enter a name for the data collector.
+
Names can contain can contain letters (a-z), numbers (0-9), dashes (-), underscores (_), apostrophes ('), and periods (.).
. Enter the Acquisition Unit to associate with this data collector.
. Enter the required fields in the Configuration screen.
. Click *Advanced Configuration* to add additional configuration fields. (Not all data collectors require advanced configuration.)
. Click *Test Configuration* to verify that the data collector is properly configured.
. Click *Add Collector* to save the configuration and add the data collector to your Cloud Insights tenant.
//For help adding a new Acquisition Unit, see //link:<task_configure_acquisition_unit>.html[C//onfiguring acquisition units]
