---
sidebar: sidebar
permalink: task_getting_started_with_cloud_insights.html
summary: Getting started with Cloud Insights.
keywords: invite, roles, data collector, acquisition unit, AU
---

= Getting started gathering data

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

After you have signed up for Cloud Insights, you must do the following in order to begin collecting and managing data.

. Install at least one Acquisition Unit
. Add data collectors

If you haven't already done so, sign in at http://cloud.netapp.com and go to your Cloud Insights tenant.

== Setting up an Acquisition Unit to collect data.

An Acquisition Unit is required to inject data into Cloud Insights. You will need to download and install the Acquisition Unit software on a server or VM to collect data for Cloud Insights.

You may set up as many Acquisition Units as needed. For example, you may want different Acquisition Units collecting information from data centers in different regions.

Instructions for link:task_configure_acquisition_unit.html[*setting up an Acquisition Unit*].

== Adding data collectors

Data collectors discover information from your data sources, such as storage devices, network switches, and virtual machines. The information gathered is used for analysis, validation, monitoring and troubleshooting. You need to link:task_configure_data_collectors.html[configure your data collectors] before Cloud Insights can gather data from them.

Related topics:
Data collector link:https://docs.netapp.com/us-en/cloudinsights/task_getting_started_with_cloud_insights.html[*configuration*]
Vendor-specific link:concept_data_collector_reference.html[*Data Collector reference*]
Troubleshooting link:task_research_failed_collector.html[*Data Collector failures*]
Data Collector link:reference_data_collector_support_matrix.html[*support matrix*]

