---
sidebar: sidebar
permalink: task_dc_na_astra_data_store.html
summary: Configure NetApp Astra Data Store
keywords: data collector, queries, create, astra, data, store,
---

= NetApp Astra Data Store data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This data collector acquires inventory and performance data for a single Astra Data Store cluster. In addition to the data collector, the Monitoring Operator will configure _Telegraf_ to collect advanced metrics and _Fluent Bit_ to collect logs.

TIP: These installation instructions and additional information can also be found in the Astra Data Store documentation:
link:https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-cloud-insights.html[Monitor metrics with Cloud Insights]
link:https://docs.netapp.com/us-en/astra-data-store/get-started/quick-start.html[Quick start for Astra Data Store]

== Terminology

Cloud Insights acquires inventory and performance data from this data collector. For each asset type acquired, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|AstraDSVolume|Internal Volume
|AstraDSNodeInfo.status.drives|Disk
|AstraDSNodeInfo|Storage Node
|AstraDSExportPolicy|Share / Share Initiator
|AstraDSCluster|Storage
|===


== Requirements

* The NetApp Monitoring Operator must be installed in the Kubernetes cluster with Astra Data Store. If this was not installed during the Astra Data Store installation, please install the monitoring operator following the Astra Data Store installation instructions.
* The _kubectl-astrads_  kubectl plugin must be installed. If it is not installed, please install the _kubectl-astrads_ binary following the Astra Data Store installation instructions.
* The following commands must be available: _awk, curl, grep and jq_.

//// 
Previous Requirements

* The Acquisition Unit must be running in a Kubernetes pod inside the Astra Data Store Kubernetes cluster. See link:task_configure_acquisition_unit.html[Acquisition Unit installation] for more details.
//Alternative text: The Acquisition Unit must be deployed by the NetApp Monitoring Operator in the Astra Data Store Kubernetes cluster. See Acquisition Unit installation for more details.
** To install the Acquisition Unit, you will need a Cloud Insights link:API_Overview.html[API Key] with Read/Write permissions to the categories: _Acquisition Unit, Data Collection, Data Ingestion_

** The Kubernetes API token used must grant read-only access to the _astrads.netapp.io_ apiGroup

* To retrieve the API token for the astrads-system default service account, run the following commands in a bash shell:

 SECRET_NAME=$(kubectl get secrets -n astrads-system| grep ^default| cut -f1 -d ' ' )
 kubectl describe secret $SECRET_NAME -n astrads-system | grep -E '^token' | cut -f2 -d':' | tr -d " "


== Configuration
[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Kubernetes API Server IP Address|The IP address of the Kubernetes API server.
|Kubernetes API Server Port|The port of the Kubernetes API server. Default is 6443.
|Kubernetes API Token|Base64 encoded Kubernetes API token.
|===

== Advanced Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Inventory Poll Interval (min)|Interval between inventory polls. The default is 60 minutes.
|Performance Poll Interval (sec)|Interval between performance polls. The default is 300 seconds. 
|Included ADS Cluster Names|Comma-separated list of ADS cluster names to include in polling. Leave blank to monitor all clusters.
|===

////

== Installation

The installation script will walk you through installation of the Astra Data Store data collector. Follow the instructions on-screen. Installation will take several minutes to complete. Once complete, it may take a few more minutes before data is shown in Cloud Insights.

The script will walk you through the following steps:

. Choose an API Access Token.
. Copy the installer script from the installation dialog and save it as as a file named _cloudinsights-ads-monitoring.sh_. You can click the clipboard icon to quickly copy the script to the clipboard.
. Open a Bash window, change directory to the location of the _cloudinsights-ads-monitoring.sh_ script.
. Copy the permissions command block from the installation dialog. You can click the clipboard icon to quickly copy the command to the clipboard.
. Paste the permissions command into the Bash window and press Enter.
. Copy the install command from the installation dialog. You can click the clipboard icon to quickly copy the command to the clipboard.
. Paste the install command into the Bash window.
. Replace <KUBERNETES_IP>  with the IP address of the Kubernetes API server.
. Replace <KUBERNETES_TOKEN>  with your Kubernetes API token.
. Press Enter.
+
The installer script will:
* Verify the Monitoring Operator is installed and configured.
* Configure Fluent Bit.
* Configure Telegraf.
* Install the Acquisition Unit.
* Install the Astra Data Store collector once the Acquisition Unit is running.

. Click _Complete Setup_.

If the installer script exits due to an error, you can rerun it again once the error is resolved. The installer script supports additional parameters such as the Monitoring Operator namespace and Kubernetes API server port if your environment does not use the default settings. A full list of available options is listed below.

=== Installer script options:

Note that the Cloud Insights domain name and selected API Access Key will be embedded in the installer script when it is downloaded. 

 $ ./cloudinsights-ads-monitoring.sh -h
 USAGE: cloudinsights-ads-monitoring.sh [OPTIONS]
 Configure monitoring of Astra Data Store by Cloud Insights.
 OPTIONS:
  -h                      Display this help message.
  -d ci_domain_name       Cloud Insights tenant domain name.
  -i kubernetes_ip        Kubernetes API server IP address.
  -k ci_api_key           Cloud Insights API Access Key.
  -n namespace            Namespace for monitoring components. (default: netapp-monitoring)
  -p kubernetes_port      Kubernetes API server port. (default: 6443)
  -r root_pv_dir          Create 3 Persistent Volumes in this directory for the Acquisition Unit.
                          Only specify this option if there is no Storage Provisioner installed and the PVs do not already exist.
  -s storage_class        Storage Class name for provisioning Acquisition Unit PVs. If not specified, the default storage class will be used.
  -t kubernetes_token     Kubernetes API server token.


//// 
Previous instructions
== Install Acquisition Unit, Telegraf, and Fluent Bit

The NetApp Monitoring Operator will be installed in the Kubernetes cluster with Astra Data Store. The Monitoring Operator manages the installation and configuration of an Acquisition Unit, a Telegraf agent for advanced metrics, and a Fluent Bit agent for logs. 

To configure the operator, follow these steps:

. Copy the custom resource definition snippet below

 spec:
   au:
     isEnabled: true
     #storageClassName: ""
   telegraf:
   - name: "open-metric"
     run-mode:
     - ReplicaSet
     substitutions:
     - key: URLS
       values:
       - "http://astrads-metrics-service.astrads-system.svc.cluster.local:9341"
     - key: METRIC_TYPE
       value: "ads-metrics"
     outputs:
     - sink: CI
   fluent-bit:
   - name: "ads-tail-ci"
     substitutions:
     - key: TAG
       value: "ads-logs"
     - key: ADS_CLUSTER_NAME
       value: "<INSERT_CLUSTER_NAME>"
     - key: LOG_FILE
       values:
       - "/var/log/firetap/*/ems/ems"
       - "/var/log/firetap/ems/*/ems/ems"
     outputs:
     - sink: CI
   output-sink:
   - api-key: "<INSERT_CI_API_KEY>"
     domain-name: "<INSERT_CI_DOMAIN_NAME>"
     name: CI

. If there is not a Storage Provisioner configured in the Kubernetes cluster, uncomment _storageClassName_ and supply the name of the StorageClass containing PVs for the Acquisition Unit. These PVs must already be created. Leave blank to use the default StorageClass.

. Replace <INSERT_CLUSTER_NAME> with the name of the Astra Data Store cluster

. Replace <INSERT_CI_API_KEY> with the Cloud Insights API Access Token

. Replace <INSERT_CI_DOMAIN_NAME> with the Cloud Insights tenant domain name

. Run the following command to edit the Monitoring Operator agent spec:
+
 kubectl --namespace netapp-monitoring edit agent acc-monitoring
 
. Merge the custom resource definition snippet above with the existing Monitoring Operator agent spec.

. Save and close the editor window.

The Monitoring Operator will now install the Acquisition Unit, Telegraf and Fluent Bit. This may take several minutes to complete.
Periodically run the following command to check the Acquisition Unit status until the status is UP. Alternatively, you can wait for the new Acquisition Unit to appear in the Cloud Insights UI.

 kubectl --namespace netapp-monitoring get agent -o jsonpath='{.status.au-pod-status}' acc-monitoring
 
Once the Acquisition Unit is installed, you may add the Astra Data Store collector from the Cloud Insights UI.

////



== Troubleshooting

Some things to try if you encounter problems with this data collector:

==== Astra Data Store data collector

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|You see an "Unauthorized" message
|Check that the Kubernetes API Token has permission to call APIs in the _astrads.netapp.io_ apiGroup
|"Unknown host: astrads-metrics-service.astrads-system.svc.cluster.local: Name or service not known"
|Verify the collector is installed in an Acquisition Unit pod running inside the ADS Kubernetes cluster.
Verify the astrads-metrics-service  is running the astrads-system  namespace.
|===

==== Installation Script

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:

|The monitoring operator is not running in <namespace> namespace.
|Follow the Astra Data Store installation instructions to install it

|Acquisition Unit pod <pod> did not start successfully after 300 seconds.
|Get the name of the acquisition unit pod: kubectl get pods --namespace netapp-monitoring \| grep "au-pod"
Check the pod events for errors: kubectl describe pod --namespace netapp-monitoring <POD_NAME>

|Acquisition Unit installation has not finished after 900 seconds
|Get the name of the acquisition unit pod: kubectl get pods --namespace netapp-monitoring \| grep "au-pod"
Check the pod logs for errors: kubectl logs --namespace netapp-monitoring <POD_NAME>
If there are no errors and the logs end with the message "Main - Acquisition is up and running!", the install succeeded but too longer than expected. Rerun the installation script. 

|Failed to retrieve Acquisition Unit id from Cloud Insights
|Verify the Acquisition Unit appears in Cloud Insights. Go to Admin > Data Collectors and click on the Acquisition Units tab.
Verify the Cloud Insights API key has permission for Acquisition Unit.

|===


Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].

