---
sidebar: sidebar
permalink: task_business_entity_annotations.html
keywords: annotations, business entity
summary: Business Entity annotations can be used for monitoring and reporting of assets in your business hierarchy
---

= Defining annotations

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create and manage business entities for your corporate environment by using the *Business Entity* annotation type. 

== Creating a Business Entity

To create a business entity, do the following:

. Click on *Manage > Annotations* and click on the _Business Entity_ link. 
+
The list of currently defined business entities is displayed.

. Click *+ Business Entity*.

. Enter values for the *Tenant*, *Line of Business*, *Business Unit*, and *Project* fields.
+
You can leave any field empty if it doesn't apply for your business entity.

. If you have previously entered a value for a field, you can select that value from the drop-down. You do not need to type it in again.

NOTE: The selected values must compose a unique total business entity. For example, if you already have a business entoty with the values _A / B / C / D_ in that order, you can not create another business entity with those values in that order. You can, however, create a business entity with those values in a different order.

== Applying a Business Entity to an Object

The easiest way to apply a business entity to an object or objects is through a query.

. Click *Queries > +New Query* and select the desired object type. You can apply filters to further narrow down the results.

. Click the checkbox to select the object(s) for which you wish to apply the business entity.

. Click *Bulk Actions* and select *Add Annotation*. 

. Choose the _Business Entity_ annotation, and select the desired business entity value from the list.

. Click *Save* to apply the business entity to the object(s).

You can also apply a business entity to an individual object by navigating to the object's asset landing page and clicking on *+Annotation) in the User Data section.

NOTE: An object can have only one business entity. 

