---
sidebar: sidebar
permalink: task_dc_emc_isilon_configure.html
keywords: data collector, isilon, EMC, DELL
summary: Configuring DELL EMC Isilon data collector.
---

= Dell EMC Isilon data collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Cloud Insights uses the Isilon SSH data collector to acquire  inventory and performance data from EMC Isilon scale-out NAS storage. 

== Terminology

Cloud Insights acquires the following inventory information from the Isilon data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|Drive|Disk
|Cluster|Storage
|Node|Storage Node
|File System|Internal Volume
|===

Note: These are common terminology mappings only and might not represent every case for this data collector. 

== Requirements

You need the following information to configure this data collector:

* Administrator permissions to the Isilon storage

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|IP address|The IP address or fully-qualified domain name of the Isilon cluster 
|User Name|User name for the Isilon cluster
|Password|Password used for the Isilon cluster
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|Inventory Poll Interval (min)|	Interval between inventory polls. The default is 20. 
|Performance Poll Interval (sec)|Interval between performance polls. The default is 300.
|SSH Process Wait Timeout|SSH process timeout period. The default is 60.
|SSH Port|SSH service port. The default is 22. 
|===