---
sidebar: sidebar
permalink: task_dc_na_cdot.html
keywords: data collector, ontap, clustered ontap, 
summary: CDOT collector
--- 

= NetApp ONTAP Data Management Software Data Collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This data collector acquires inventory and performance data from storage systems running Clustered Data ONTAP using read-only API calls from an administrator account.

== Terminology

Cloud Insights acquires inventory and performance data from the Clustered Data ONTAP data collector. For each asset type acquired, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|Disk|Disk
|Raid Group|Disk Group
|Cluster|Storage
|Node|Storage Node
|Aggregate|Storage Pool
|LUN|Volume
|Volume|Internal Volume
|===

== Requirements

The following are requirements to configure and use this data collector:

* You must have access to an Administrator account used for read-only API calls.
* Username (with read-only role name to ontapi application to the default Vserver) and password to log into NetApp cluster)
* Port requirements: 80 or 433
* License requirements:
** FCP license and mapped/masked volumes required for discovery 

== Configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|NetApp Management IP |IP address or fully-qualified domain name of the NetApp cluster
|User Name |User name for NetApp cluster
|Password |Password for NetApp cluster 
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Communication Port|Port used for NetApp API
|Inventory Poll Interval (min) |Default is 60 minutes.
|Performance Poll Interval (sec)|Default is 900 seconds.
|===
