---
sidebar: sidebar
permalink: task_cs_user_management.html
keywords: Cloud Secure, User, Login, account
summary: Cloud Secure User accounts are managed through Cloud Insights User management
---

= User Management

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
Cloud Secure user accounts are managed through Cloud Insights.

Cloud Insights provides four user account levels: Account Owner, Administrator, User, and Guest. Each account is assigned specific permission levels. A User account that has Administrator privileges can create or modify users, and assign each user one of the following Cloud Secure roles: 

|===
|Role	|Cloud Secure	Access
|Administrator	
|Can perform all Cloud Secure functions, including those for Alerts, Forensics, data collectors, automated response policies, and APIs for Cloud Secure.
An Administrator can also invite other users but can only assign Cloud Secure roles.
|User	
|Can view and manage Alerts and view Forensics. User role can change alert status, add a note, take snapshots manually, and restrict user access.
|Guest	
|Can view Alerts and Forensics. Guest role cannot change alert status, add a note, take snapshots manually, or restrict user access.

|===

.Steps

. Log into Cloud Secure
. In the menu, click *Admin > User Management*
+
You will be forwarded to Cloud Insights’s User Management page.

. Select the desired role for each user.

While adding a new user, simply select the desired role (usually User or Guest).

More information on User accounts and roles can be found in the Cloud Insights link:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html[User Role] documentation.
