---
sidebar: sidebar
permalink: task_kubernetes_operator_proxy.html
keywords: telegraf, installation, install, agent, telegraf agent
summary: Cloud Insights supports link:https://docs.influxdata.com/telegraf/v1.19/[Telegraf] as its agent for collection of integration data and can be configured on Windows, Linux, macOS, and Kubernetes. 
---

= Configuring an Agent to Collect Data

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]



Using a custom/private docker repository
Setting up a proxy
A proxy can be configured for the monitoring operator in the CR starting with the CI deployment that went into production on 
10 Dec 2021
10 Dec 2021 

kubectl -n netapp-monitoring edit agent agent-monitoring-netapp


In the spec: section of this file, add the following code block

spec:
  proxy:
    isAuProxyEnabled: <true or false>
    isTelegrafProxyEnabled: <true or false>
    isFluentbitProxyEnabled: <true or false>
    password: <password for proxy, optional>
    port: <port for proxy>
    server: <server for proxy>
    username: <username for proxy, optional>
    noProxy: <comma separated list of IPs or resolvable hostnames that should bypass a proxy>
Using a custom/private docker repository
Get the docker secret

kubectl -n netapp-monitoring get secret docker -o yaml
 
(copy paste the value of .dockerconfigjson: from the output of the above command)
Decode the docker secret

echo <paste from step #1 above> | base64 -d
The output of this will be in the following json format:
{ "auths":
   {"docker.<cluster>.cloudinsights.netapp.com" :
     {"username":"<tenant id>",
      "password":"<password which is the CI API key>",
      "auth"    :"<encoded username:password basic auth key. This is internal to docker>"}
   }
}
login to docker repository

docker login docker.<cluster>.cloudinsights.netapp.com (from step #2) -u <username from step #2>
password: <password from step #2>
pull the operator docker image from Cloud Insights

docker pull docker.<cluster>.cloudinsights.netapp.com/netapp-monitoring:<version>
 
Find the <version> field using the following command:
 
kubectl -n netapp-monitoring get deployment monitoring-operator | grep "image:"
push the operator docker image to your private/enterprise docker registry

Push the code to your private/local/enterprise docker repository according to your corporate policies
Download all open source dependencies to your private docker registry

The following open source images need to be downloaded:
docker.io/telegraf:1.19.3
gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.0
 
If fluent-bit is enabled:
docker.io/fluent-bit:1.7.8
docker.io/kubernetes-event-exporter:0.10
Edit the agent CR to reflect the new docker repo location, disable auto upgrade (if enabled)

kubectl -n netapp-monitoring edit agent agent-monitoring-netapp
 
enableAutoUpgrade: false
docker-repo: <docker repo of the enterprise/corp docker repo>
dockerRepoSecret: <optional: name of the docker secret of enterprise/corp docker repo, this secret should be already created on the k8s cluster in the same namespace>
 
In the spec: section, make the following changes:
 
spec:
  telegraf:
    - name: ksm
      substitutions:
        - key: k8s.gcr.io
          value: <same as "docker-repo" field above>
