---
sidebar: sidebar
permalink: task_dc_aws_configure.html
keywords: data collector, AWS EC2, 
summary: Configuring AWS EC2 data collector.
---

[.lead]

Cloud Insights uses the Amazon AWS EC2 data collector to collect inventory and performance data. 

.Before you begin

In order to collect data from Amazon AWS EC2 devices, you must have the following information: 

* You must have the IAM Access Key ID 
* You must have the Secret Access Key for your Amazon AWS EC2 cloud account

Access keys consist of an access key ID (for example, AKIAIOSFODNN7EXAMPLE) and a secret access key (for example, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY). You use access keys to sign programmatic requests that you make to AWS if you use the AWS SDKs, REST, or Query API operations. 

These keys are provided with your contract.   

Enter data into the data source fields according to the table below:

*Configuration*

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|AWS Region|Choose AWS region
|AWS IAM Access Key ID|Enter AWS IAM Access Key ID
|AWS IAM Secret Access Key|Enter AWS IAM Secret Access Key 
|I understand AWS bills me for API requests|heck this to verify your understanding that AWS bills you for API requests made by Insight polling
|===

*Advanced Configuration*

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Inventory Poll Interval (min)|(default 60 min)
|HTTP connection and socket timeout|(default 300 sec)
|Include AWS tags|Check to enable support for AWS tags in Cloud Insights annotations.
|Performance Poll Interval|(default 1800 seconds)
|===

== Mapping AWS tags to Cloud Insights annotations

The AWS EC2 data collector includes an option that allows you to populate Cloud Insights annotations with tags configured on AWS. The annotations must be named exactly as the AWS tags. Cloud Insights will always populate same-named text-type annotations, and will make a "best attempt" to populate annotations of other types (number, boolean, etc). If your annotation is of a different type and the data collector fails to populate it, it may be necessary to remove the annotation and re-create it as a text type.

Note that AWS is case-sensitive, while Cloud Insights is case-insensitive. So if you create an annotation named "OWNER" in Cloud Insights, and tags named "OWNER", "Owner", and "owner" in AWS, all of the AWS variations of "owner" will map to Cloud Insight's "OWNER" annotation. 

.Related Information
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Managing Access Keys for IAM Users^]



