---
sidebar: sidebar
permalink: task_create_annotation.html
keywords: annotations, annotation rules, manual annotations,
summary: This topic describes how to create an annotation.
---

= Creating annotations

:toc: macro
:hardbreaks: AA
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You create annotations and assign them to assets you monitor. Annotations are notes that provide information about an asset, such as physical location, end of life, storage tier, or volume service levels.

You can assign annotations either manually or by defining and applying link:task_create_annotation_rules.html[annotation rules].

== Defining annotations 

Using annotations, you can add custom business-specific data that matches your business needs to assets. While Cloud Insights provides a set of default annotations, such as asset life cycle (birthday or end of life), building or data center location, and tier, you might find that you want to view data in other ways.

The data in custom annotations supplements device data already collected, such as switch manufacturer, number of ports, and performance statistics. The data you add using annotations is not discovered by Cloud Insights.

toc::[]

== Manually assigning annotations to assets

.Before you begin
* List any industry terminology to which environment data must be associated.
* List corporate terminology to which environment data must be associated, which is not already being tracked using the business entities.
* Identify any default annotation types that you might be able to use.
* Identify which custom annotations you need to create.
You need to create the annotation before it can be assigned to an asset.

Use the following steps to create an annotation.

.Steps
. In the Cloud Insights menu, click *Manage > Annotations*
. Click *+ Annotation* to create a new annotation.
. Enter a Name, Description, and type for the new annotation.
+
For example, enter the following to create a text annotation that defines the
physical location of an asset in Data Center 4:

. Enter a name for the annotation (such as "Location")
. Enter a description of what the annotation is describing (such as "Physical location is Data Center 4")
. Enter the 'type' of annotation it is (Text).


