---
sidebar: sidebar
permalink: task_defining_annotations.html
keywords: annotations, monitor, notes, tags
summary: You can customize Cloud Insight to track data for your corporate requirements using specialized notes, called annotations, and assign them to your assets. 
---

= Using annotations to monitor your environment

[.lead]
When customizing Cloud Insights to track data for your corporate requirements, you can define specialized notes, called annotations, and assign them to your assets.

toc::[]

You can assign annotations to assets with information such as asset end of life, data center, building location, storage tier, or volume service level.

Using annotations to help monitor your environment includes the following high-level tasks: 

* Creating or editing definitions for all annotation types. 
* Displaying asset pages and associating each asset with one or more annotations. 
+ 
For example, if an asset is being leased and the lease expires within two months, you might want to apply an end-of-life annotation to the asset. This helps prevent others from using that asset for an extended time. 

* Creating rules to automatically
apply annotations to multiple assets of the same type.
* Using the annotation import utility to import annotations.
* Filter assets by their annotations.

== Default annotation types

Cloud Insights provides some default annotation types. These annotations can be used to filter or group data. 

You can associate assets with default annotation types such as the following: 

* Asset life cycle, such as birthday, sunset, or end of life 
* Location information about a device, such as data center, building, or floor
* Classification of assets, such as by quality (tiers), by connected devices (switch level), or by service level
* Status, such as hot (high utilization) 

The following table lists the default annotation types. You can edit any of these annotation names to suit your needs. 

[cols=3*, Optiosn="header",cols="30,53, 16"]
|===
|Annotation types
|Description
|Type
|Alias|User-friendly name for a resource|Text
|Compute Resource Group|Group assignment used by host/VM collection data collector|List
|Data Center|Physical location|List
|Hot|Over-utilized devices|Boolean
|Note|Comments associated with a resource|Text
|Service Level|A set of supported service levels that you can assign to resources. Provides an ordered options list for internal volumes, qtree, and volumes. Edit service levels to set performance policies for different levels.|List
|Sunset|No new allocations past this date.|Date
|Switch Level|Predefined options for setting up categories for switches. Typically, these designations remain for the life of the device, although you can edit them. Available only for switches.|List
|Tier|Can be used to define different levels of service within your environment. Tiers can define the type of level, such as speed needed (for example, gold or silver). This feature is available only on internal volumes, qtrees, storage arrays, storage pools, and volumes.|List
|Violation Severity|Rank (for example, major) of a violation (for example, missing host ports or missing redundancy), in a hierarchy of highest to lowest importance.|List
|===
NOTE: Alias, Data Center, Hot, Service Level, Sunset, Switch Level,  Tier, and Violation Severity are system-level annotations, which you cannot delete or rename; you can change only their assigned values.

== Creating custom annotations

Using annotations, you can add custom business-specific data that matches your business needs to assets. While Cloud Insights provides a set of default annotations, you might find that you want to view data in other ways. The data in custom annotations supplements device data already collected, such as switch manufacturer, number of ports, and performance statistics. The data you add using annotations is not discovered by Cloud Insights. 

.Steps

. In the Cloud Insights menu, click *Manage > Annotations*. 
+
The Annotations page displays the list of annotations. 
. Click *+Add* 
. Enter a *Name* and *Description* of the annotation.
+
You can enter up to 255 characters in these fields.
. Click *Type* and then select one of the following options that represents the type of data allowed in this annotation:

.Annotation types
Boolean:: This creates a drop-down list with the choices of yes and no. For example, the "Direct Attached" annotation is Boolean.
Date:: This creates a field that holds a date. For example, if the annotation will be a date, select this.
List:: Creates either of the following: 
* A drop-down fixed list
+
When others are assigning this annotation type on a device, they cannot add more values to the list. ???
* A drop-down flexible list 
+
If you select the Add new values on the fly option when you create this list, when others are assigning this annotation type on a device, they can add more values to the list.

Number:: This creates a field where the user assigning the annotation can enter a number. For example, if the annotation type is "Floor", the user could select the Value Type of "number" and enter the floor number.

Text:: This creates a field that allows free-form text. For example, you might enter "Language" as the annotation type, select "Text" as the value type, and enter a language as a value.
+
With a text-type annotation, you can also include a hyperlink. Hyperlinks must follow one of the following formats:
+
* Direct link, no formatting:
+
 http://www.netapp.com
 https://clouddocs.netapp.com

* Link with text formatting:
+
 [Your Text Here](http://cloud.netapp.com)
 
* Link to a page (for example a dashboard) in your environment:
+
 [Your Text Here](#/dashboards/<dashboardID>)

NOTE: After you set the type and save your changes, you cannot change the type of the annotation. If you need to change the type, you have to delete the annotation and create a new one.

If you select List as the annotation type, do the following: 

. Select *Add new values on the fly* if you want the ability to add more values to the annotation when on an asset page, which creates a flexible list.
+
For example, suppose you are on an asset page and the asset has the City annotation with the values Detroit, Tampa, and Boston. If you selected the Add new values on the fly option, you can add additional values to City like San Francisco and Chicago directly on the asset page instead of having to go to the Annotations page to add them. If you do not choose this option, you cannot add new annotation values when applying the annotation; this creates a fixed list.

. Enter a value and description in *Value* and  *Description* fields. 

. Click *+Add+* to add additional values. 

. Click the Trash icon to delete a value.

. Click *Save* 
+
Your annotations appear in the list on the Annotations page.

.After you finish 
In the web UI, the annotation is available immediately for use. 

