---
sidebar: sidebar
permalink: task_research_failed_collector.html
keywords: data collector, changes, failures
summary: Data collector errors need to be researched and corrected to ensure continued collection of data.
---

= Researching a failed data collector

[.lead]
If a data collector has a failure message, you can research the problem using the data collector page with its linked information.

Use the following steps to determine the cause of a failed data collector. Data Collector failures are noted on the *Admin* menu and on the *Installed Data Collectors* page as a number highlighted in red, indicating the number of failures. 

.Steps 

. Click *Admin* > *Data Collectors* > *Installed Data Collectors*. 
. Click the linked Name of the failing data collector to open the Data Collector's *Summary* page.
. On the Summary page, check the *Comments* area to read any notes left by another engineer who might also be investigating this failure.
. Note any performance messages.
//. If there is a patch being applied to this data collector, click link to check the patch page to see if that has caused the problem.
. Move your mouse pointer over the segments of the *Event Timeline* graph to display additional information.
. Select an error message for a Device displayed below the Event Timeline, and click the *Error Details* link that displays to the right of the message.
+
The Error Details includes the text of the error message, most likely causes, information in use, and suggestions of what can be tried to correct the problem.

. In the *Devices Reported By This Data Collector* area, you can filter the list to display only devices of interest, and you can click the linked *Name* of a device to display the asset page for that device.
. When you return to the data collector summary page, check the *Most Recent Changes* area at the bottom of the page to see if recent changes could have caused the problem.
