---
sidebar: sidebar
permalink: task_add_collector_svm.html
keywords:  data collector, ONTAP, NetApp, SVM, cloud ontap, firewall
summary: Adding data collectors
---

= Configuring the NetApp ONTAP Data Collector 

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Cloud Secure uses data collectors to collect file and user access data from devices. 

.Before you begin

* This data collector is supported on Data ONTAP 9.1 and later versions. 

* An Agent must be configured before you can configure data collectors. See link:task_add_agent.html[Configuring an agent] for instructions. 

* A separate subnet must be used for FPolicy traffic.

* You need the SVM management IP address.
* You need a username and password to access the SVM.
* Ensure the correct protocols are set for the SVM.

** security login show -vserver causer
+
Vserver: causer
Authentication Acct Is-Nsswitch
User/Group Name Application Method Role Name Locked Group
+
vsadmin http password vsadmin yes no
+
vsadmin ontapi password vsadmin yes no
+
vsadmin ssh password vsadmin yes no
+
3 entries were displayed.

* Set a password for the SVM
+
clustershell::> security login password -username vsadmin -vserver causer

* Unlock the SVM for external access:
+
clustershell::> security login unlock -username vsadmin -vserver causer

*  Verify that the ONTAP FPolicy framework can connect to the External FPolicy server engine that the Agent system hosts:
+
clustershell::*> vserver fpolicy show-engine -vserver causer
+
The agent IP address state should be "Connected".

* When a firewall is enabled, you must have an exception defined to allow TCP traffic for the port using the Data ONTAP Data Collector. See link:concept_agent_requirements.html[Agent requirements] for configuration information. This applies to on-premise Agents and Agents installed in the Cloud.  

* When an Agent is installed in an AWS EC2 instance to monitor a Cloud ONTAP SVM, the Agent and Storage must be in the same VPC. If they are in separate VPCs, there must be a valid route between the VPC’s.

Create the following roles for the data collector: 

* security login show -vserver vs1
* security login role create -vserver vs1 -role carole -cmddirname DEFAULT -access none
* security login role create -vserver vs1 -role carole -cmddirname "network interface" -access readonly
* security login role create -vserver vs1 -role carole -cmddirname version -access readonly
* security login role create -vserver vs1 -role carole -cmddirname volume -access readonly
* security login role create -vserver vs1 -role carole -cmddirname vserver -access readonly
* security login role create -vserver vs1 -role carole -cmddirname "vserver policy" -access all 
* security login create -user-or-group-name causer -application ontapi -authmethod password -role carole -vserver vs1


 
.Steps for Configuration 

. Log in as Administrator or Account Owner to your Cloud Secure environment. 
. Click *Admin > Data Collectors > +Data Collectors* 
+
The system displays the available Data Collectors. 

. Click *+Monitor* in the *NetApp ONTAP SVM* tile.  
+ 
The system displays the Add SVM configuration page. Enter the required data for each field. 

[caption=]
.Configuration
[cols=2*, cols"50,50"]
[Options=header]
|===
|*Name* |*Field*
|Name |Unique name for the Data Collector
|Agent|Select a configured agent from the list or click *Add Agent* to configure an Agent. See link:concept_agent_requirements.html[Agent requirements] and 
link:task_add_agent.html[Configuring an Agent] for configuration information.
|SVM Management IP Address|Management IP Address
|Username|User name to access the SVM
|Password|SVM Password
|===

// [caption=]
//Advanced Configuration 
//[cols=2*, cols"50,50"]
//[Options=header]
//|===
//|*Name* |*Field*
//|Protocol| HTTPS
//|Ports | 443
//|===

// [caption=]
//.Custom NFS Export Policies and CIFS Shares
//[cols=2*, cols"50,50"]
//[Options=header]
//|===
//|*Name* |*Field*
//|NFS Export Policies| All included or All excluded
//|Policy 1 | Included or Excluded
//|Policy 2 | Included or Excluded
//|Policy 3 | Included or Excluded
//|Newly added NFS Export Policies | Include or exclude
//|CIFS Shares|All included or All excluded
//|Share 1 |Included or Excluded
//|Share 2 |Included or Excluded
//|Share 3 |Included or Excluded
//|Newly added CIFS Shares | Include or exclude
//|===




.After you finish

Click *Test Configuration* to check the status of the collector you configured.
