---
sidebar: sidebar
permalink: task_cloud_insights_onboarding_1.html
summary: Signing up for Cloud Insights and creating a tenant.
---
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

= Cloud Insights Onboarding

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help, onboarding, getting started

[.lead]
Before you can start working with Cloud Insights, you must sign up on the NetApp Cloud Central portal. If you already have a NetApp Cloud login, you can start a free trial of Cloud Insights with a few quick steps.

toc::[]

== Signing up on NetApp Cloud Central

To sign up for access NetApp's cloud services, go to https://cloud.netapp.com[NetApp Cloud Central^] and click *Sign Up*.

Enter a valid email address and choose a password.
Enter your company name, and your full name.
Accept the terms and conditions and click *Sign Up*.

You will then be taken to NetApp's cloud offerings page.

== What if I already have a NetApp Cloud login?

If you already have a NetApp Cloud Central account, simply choose *Log In* on the https://cloud.netapp.com[NetApp Cloud Central^] portal page.

Enter your email address and password. You will then be taken to NetApp's cloud offerings page.

On the Cloud offerings page, choose *Go to Cloud Data Services*.

== Starting your Cloud Insights free trial

If this is your first time logging in to Cloud Insights, under the Cloud Insights offering, click on *Start Free Trial*, which will kick off a free, 14-day trial of Cloud Insights. All Cloud Insights features are available during the trial period.

After starting your free trial, you will be prompted to answer a few questions about your environment. Cloud Insights will then create your company's tenant based on your responses. Once the tenant has been created, you will be automatically logged in to it.

== Sign in and go

Once your tenant has been created, after signing in, click *Go to Cloud Insights*. You will be taken directly to your Cloud Insights tenant. After the free trial has ended, Cloud Insights will use the features based on your current license.
