---
sidebar: sidebar
permalink: task_dc_emc_clariion.html
keywords: data collector, EMC, clariion
summary: Configuring DELL EMC Clariion.
---

= Dell EMC CLARiiON (NaviCLI) data collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Cloud Insights uses the Dell EMC CLARiiON (NaviCLI) data collector to  acquire inventory and performance data.



== Terminology

Cloud Insights acquires the following inventory information from the EMC CLARiiON data collector. For each asset type acquired by Cloud  Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|Disk|Disk
|Storage|Storage
|Storage Processor|Storage Node
|This Pool, RAID Group|Storage Pool
|LUN|Volume
|===

Note: These are common terminology mappings only and might not represent every case for this data source. 

== Requirements

The following requirements must be met in order to collect data:

* An IP address of each CLARiiON storage processor
* Read-only Navisphere username and password to the CLARiiON arrays
* NaviCLI must be installed on the Cloud Insights AU
* Access validation: Run NaviCLI from the Cloud Insights AU to each array using the username and password.
* Port requirements: 80, 443
* NaviCLI version should correspond with the newest FLARE code on your array
* For performance, statistics logging must be enabled.

== NaviSphere command line interface syntax

naviseccli.exe -h <IP address> -user <user> -password <password> -scope
<scope,use 0 for global scope> -port <use 443 by default> command

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field |Description
|CLARiiON storage|IP address or fully-qualified domain name of the CLARiiON Storage
|User Name |Name used to log into the CLARiiON storage device. 
|Password|Password used to log into the CLARiiON storage device. 
|CLI Path|Full path to the _navicli.exe_ OR _naviseccli.exe_  executable
|===

== Advanced Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field |Description
|Inventory Poll Interval (min)|Interval between inventory polls. Default is 40 minutes.
|Use Secure Client |Select to use the _navseccl_ secure client (i)
|Scope|The secure client scope. The default is Global.
|CLARiiON CLI Port|Port used for CLARiiON CLI. The default is 443. 
//|Inventory External Process Timeout (sec)|External process timeout. The default is 1800 seconds.
|Performance Poll Interval (sec)|Interval between performance polls. The default is 300 seconds. 
//|Performance External process timeout (sec)|External process timeout. The default is 1800 seconds.
|===

== Troubleshooting
Some things to try if you encounter problems with this data collector:

==== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|Error:
•	Agent Not Running
•	Failed to find naviseccli
•	Failed to execute any command
|Possible solutions:
•	Confirm that NaviSphere CLI is installed on the Cloud Insight Acquisition Unit
•	You have not selected the "Use secure client" option in the data collector configuration wizard and do not have a non-secure version of Naviphere CLI installed.
•	Confirm that NaviSphere CLI installation directory is correct in the data collector configuration
•	Confirm that the IP of the CLARiiON is correct in the data collector configuration:
•	From the Cloud Insights Acquisition Unit:
    -	Open a CMD.
    -	Change the directory to the configured installation directory
    -	Try to make a connection with the CLARiiON device by typing “navicli -h {ip} getagent” (replace the {ip} with the actual IP)
|Error: 4.29 emc235848 emc241018 getall Failed to parse host alias info
|This is likely caused by a FLARE 29 corruption issue of the host initiator database on the array itself. See EMC knowledge base articles: emc235848, emc241018. You can also check https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128
|Error: Unable to retrieve Meta LUNs. Error Executing java -jar navicli.jar
|Possible Solutions:
•	Modify the data collector configuration to use the secure client (recommended)
•	Install navicli.jar in the CLI path to navicli.exe OR naviseccli.exe
•	Note: navicli.jar is deprecated as of EMC Navisphere version 6.26
•	The navicli.jar may be available on http://powerlink.emc.com
|Error: Storage Pools not reporting disks on Service Processor at configured IP address
|Configure the data collector with both Service Processor IPs, separated by a comma
|Error: Revision mismatch error
|Possible solutions: 
•	This is usually caused by updating the firmware on the CLARiiON device, but not updating the installation of NaviCLI.exe. This also might be caused by having different devices with different firmwares, but only one CLI installed (with a different firmware version).
•	Verify that the device and the host are both running identical versions of the software:
    -	From the Cloud Insights Acquisition Unit, open a command line window
    -	Change the directory to the configured installation directory
    -	Make a connection with the CLARiiON device by typing “navicli -h ${ip} getagent”
    -	Look for the version number on the first couple of lines. Example: “Agent Rev:           6.16.2 (0.1)”
    -	Look for and compare the version on the first line. Example: “Navisphere CLI Revision 6.07.00.04.07”
|Error: Unsupported Configuration - No Fibre Channel Ports
|Possible solution: The device is not configured with any Fibre Channel ports. Currently, only FC configurations are supported.  Verify this version/firmware is supported.
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].


