---
sidebar: sidebar
permalink: task_create_application.html
summary: You define applications which you then apply to assets on your tenant as needed.
keywords: application, create application,
---

= Creating Applications
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To track data associated with specific applications running on your tenant, you can define the applications in Data Infrastructure Insights.

.Before you begin

If you want to associate the application with a business entity, you must create the business entity before you define the application.

.About this task

Data Infrastructure Insights allows you to track data from assets associated with applications for things like usage or cost reporting. 

.Steps


. In the Data Infrastructure Insights menu, click *Observability > Enrich > Applications*. Select 

+
The Add Application dialog box displays.

. Enter a unique name for the application.
. Select a priority for the application.
. Click *Save*.

After defining an application, it can be assigned to assets.

== Assigning applications to assets

This procedure assigns the application to a host as an example. You can assign host, virtual machine, volume, or internal volumes to an application. 

.Steps

. Locate the asset to which you want to assign to the application:
. Click *Queries > +New Query* and search for Host.
. Click the check box on the left of the Host you want to associate with the application.
. Click *Bulk Actions > Add Application*.
. Select the Application you are assigning the asset to. 

Any new applications you assign override any applications on the asset that were derived from another asset. For example, volumes inherit applications from hosts, and when new applications are assigned to a volume, the new application takes precedence over the derived application.

NOTE: For environments with large amounts of related assets, inheritance of application assignments to those assets could take several minutes. Please allow more time for inheritance to occur if you have many related assets.

.After you finish

After assigning the host to the application you can assign the remaining assets to the application. To access the landing page for the application, click *Manage > Application* and select the application you created. 


