---
sidebar: sidebar
permalink: task_dc_emc_datadomain_configure.html
keywords: data collector, Data Domain, EMC, DELL
summary: Configuring DELL EMC Data Domain data collector.
---

= DELL EMC Data Domain data collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This data collector gathers inventory and performance information from DELL EMC Data Domain deduplication storage systems. To configure this data collector, there are specific configuration instructions and usage recommendations you must follow. 

== Terminology

Cloud Insights acquires the following inventory information from the Data Domain data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|Disk|Disk
|Array|Storage
|FC Port|Port
|File System|Internal Volume
|Quota|Quota
|NFS and CIFS share|FileShare
|===

Note: These are common terminology mappings only and might not represent every case for this data colletor.

== Requirements

You need the following information to configgure this data collector:

* Read-only user name and password to the Data Domain storage 

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|IP address|The IP address or fully-qualified domain name of the Data Domain storage array 
|User name|The user name for the Data Domain storage array
|Password|The password for the Data Domain storage array 
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description 
|Inventory Poll Interval (min)|Interval between inventory polls. The default is 20. 
|SSH Process Wait Timeout (sec)|SSH process timeout. The default is 180.
|SSH Port|SSH service port 