---
sidebar: sidebar
permalink: task_dc_na_hostvm.html
keywords: data collector, NetApp, OpenStack 
summary: NetApp Host and VM File Systems data collector.
---

= NetApp Host and VM File Systems data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead] 

Use the NetApp Host and VM File Systems data collector to retrieve file system details and storage resource mappings for Microsoft Windows host and VM file systems and for supported Linux VMs that are annotated with the configured Compute Resource Group (CRG).

== General Requirementssource

*  Use the support matrix to verify that your host or virtual machine operating system is supported. 
* To verify that links from file systems to storage resources are created, check that the relevant storage or virtualization vendor type and version report the volume or virtual disk identification data required.

== Microsoft Windows Requirements 

* This data collector uses Window Management Instrumentation (WMI) data structures to retrieve data. 
+
This service must be operational and available remotely. In particular, port 135 must be accessible and must be opened if behind a firewall.

* Windows domain users must have the appropriate permissions to access WMI structures.
* Administrator permissions are required.

== Linux Requirements

* This data collector uses a Secure Shell (SSH) connection to execute commands on Linux VMs. 
+
The SSH service must be operational and available remotely. In particular, port 22 must be accessible and must be opened if behind a firewall.

* SSH users must have sudo permissions to execute read-only commands on Linux VMs. 
+
You must use the same password to log in to SSH and to answer any sudo password challenge.

== Usage reccomendations

* You should annotate a group of hosts and virtual machines that have common operating system credentials using the same Compute Resource Group annotation. 
+
Each group has an instance of this data collector discovering file system details from those hosts and virtual machines. 

* If you have an instance of this data collector for which the success rate is low (for example, Cloud Insights is discovering file system details for only 50 of 1000 hosts and virtual machines in a group), you should move the hosts and virtual machines for which discovery is successful into a separate Compute Resource Group.

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|User Name|Operating system user with appropriate rights to retrieve file system data. For Windows operating system users, this must include the domain prefix.
|Password|Password for the operating system user
|Compute Resource Group|Annotation value used to flag host and virtual machines for the data source discovered file systems.

A blank value indicates that the data collector discovers file systems for all hosts and virtual machines not currently annotated with a Compute Resource Group.
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Inventory poll interval (min)|Interval between inventory polls. The default is 360 minutes.
|===
