---
sidebar: sidebar
permalink: task_dc_na_cdot.html
keywords: data collector, ontap, clustered ontap
summary: CDOT collector
--- 

= ONTAP Data management data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This data collector acquires inventory and performance data from storage systems running ONTAP Data management software using read-only API calls from an administrator account.

== Terminology

Cloud Insights acquires inventory and performance data from the ONTAP Data management software data collector. For each asset type acquired, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|Disk|Disk
|Raid Group|Disk Group
|Cluster|Storage
|Node|Storage Node
|Aggregate|Storage Pool
|LUN|Volume
|Volume|Internal Volume
|===

== Requirements

The following are requirements to configure and use this data collector:

* You must have access to an Administrator account used for read-only API calls.
* Target IP is the cluster management LIF.
* FCP license and mapped/masked volumes required for Cloud Insights discovery.
* CIFS and/or NFS license and CIFS shares or NFS exports required for Cloud Insights NAS discovery.
* Access validation: Telnet or SSH to the cluster management LIF from the acquisition unit, using the username and password.

== Configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|NetApp Management IP |IP address or fully-qualified domain name of the NetApp cluster
|User Name |User name for NetApp cluster
|Password |Password for NetApp cluster 
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Communication Port|Port used for NetApp API
|Inventory Poll Interval (min) |Default is 20 minutes.
|Performance Poll Interval (sec)|Default is  300 seconds.
|===
