---
sidebar: sidebar
permalink: task_dc_amazon_ec2.html
keywords: data collector, EC2, 
summary: Configuring Amazon EC2 data collector.
---

= Configuring the Amazon EC2 data collector


:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]

Cloud Insights uses the Amazon EC2 data collector to acquire inventory and performance data from EC2 instances. 


== Requirements

In order to collect data from Amazon EC2 devices, you must have the following information: 

* You must have the IAM Access Key ID 
* You must have the Secret Access Key for your Amazon EC2 cloud account
* Port 433 HTTPS
* EC2 Instances can be reported as a Virtual Machine, or (less naturally) a Host. EBS Volumes can be reported as both a VirtualDisk used by the VM, as well as a DataStore providing the Capacity for the VirtualDisk.

Access keys consist of an access key ID (for example, AKIAIOSFODNN7EXAMPLE) and a secret access key (for example, wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY). You use access keys to sign programmatic requests that you make to EC@ if you use the Amanzon EC2 SDKs, REST, or Query API operations. These keys are provided with your contract from Amazon.   


== Configuration

Enter data into the data collector fields according to the table below:

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|AWS Region|Choose AWS region
|AWS IAM Access Key ID|Enter AWS IAM Access Key ID
|AWS IAM Secret Access Key|Enter AWS IAM Secret Access Key 
|I understand AWS bills me for API requests|Check this to verify your understanding that AWS bills you for API requests made by Cloud Insights polling.
|===

== Advanced Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field | Description
|Inventory Poll Interval (min)|The default is 60
//|HTTP connection and socket timeout (sec)|The default is 300
|Include AWS tags|Check to enable support for AWS tags in Cloud Insights annotations.
|Performance Poll Interval (sec)|The default is 1800
|===

== Mapping Amazon tags to Cloud Insights annotations

The Amazon EC2 data collector includes an option that allows you to populate Cloud Insights annotations with tags configured on EC2. The annotations must be named exactly as the EC2 tags. Cloud Insights will always populate same-named text-type annotations, and will make a "best attempt" to populate annotations of other types (number, boolean, etc). If your annotation is of a different type and the data collector fails to populate it, it may be necessary to remove the annotation and re-create it as a text type.

Note that AWS is case-sensitive, while Cloud Insights is case-insensitive. So if you create an annotation named "OWNER" in Cloud Insights, and tags named "OWNER", "Owner", and "owner" in EC2, all of the EC2 variations of "owner" will map to Cloud Insight's "OWNER" annotation. 

.Related Information

* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Managing Access Keys for IAM Users^]

////
== Troubleshooting

Information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].
////


