---
sidebar: sidebar
permalink: task_cloud_insights_onboarding_1.html
summary: Signing up for Cloud Insights and creating a tenant.
---

= Cloud Insights Onboarding

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help, onboarding, getting started

[.lead]
Before you can start working with Cloud Insights, you must sign up on the NetApp Cloud Central portal. If you already have a NetApp Cloud login, you can start a free trial of Cloud Insights with a few quick steps.

toc::[]

== Creating your NetApp Cloud Central account

To sign up for access to NetApp's cloud services, go to https://cloud.netapp.com[NetApp Cloud Central^] and click *Sign Up*.

* Enter a valid email address and choose a password.
* Enter your company name, and your full name.
* Accept the terms and conditions and click *Sign Up*.

You will then be taken to NetApp's cloud offerings page.

On the Cloud offerings page, choose *Go to Cloud Data Services*.

=== What if I already have a NetApp Cloud login?

If you already have a NetApp Cloud Central account, simply choose *Log In* on the https://cloud.netapp.com[NetApp Cloud Central^] portal page.

Enter your email address and password. You will then be taken to NetApp's cloud offerings page.

On the Cloud offerings page, choose *Go to Cloud Data Services*.

== Starting your Cloud Insights free trial

If this is your first time logging in to Cloud Insights, under the Cloud Insights offering, click on *Register*. You will be prompted to answer a few questions and request a name for your tenant. Cloud Insights will then create your company's tenant based on your responses. You will receive an email when your tenant creation is complete.

NOTE: If the requested tenant name is already in use, you will be offered suggestions for a new name. You may choose one of these or enter a different name.

//Tenant creation takes a few moments to complete. During this time, you will be asked a few additional questions about your environment and what you'd like to get out of Cloud Insights. Your answers are voluntary but will help shape the Cloud Insights service.

Once the creation of your tenant is complete, you can use your Cloud Central credentials to log in and start your free, 14-day trial of Cloud Insights. All Cloud Insights features are available during the trial period. 

During the free trial, you can link:concept_subscribing_to_cloud_insights.html[start your subscription] to Cloud Insights at any time. After the free trial has ended, Cloud Insights will use the features based on your current subscription.

== Sign in and go

Once your tenant has been created, you can simply log in to the NetApp Cloud Portal and click *Go to Cloud Insights*. You will be taken directly to your Cloud Insights tenant.

You can also open a browser directly to your Cloud Insights tenant URL:

 https://<your-tenant-name>.cloud.netapp.com/

The URL will also be included in each user's invitation email for simple access and bookmarking.  If you are not already logged in to Cloud Central, you will be prompted to log in.

NOTE: New users must still sign up for access to Cloud Central before they can access their tenant URL.

== Logging Out

To log out of Cloud Insights, click your *User Name* and select *Log Out*. You will be taken back to the Cloud Central sign in screen.

NOTE: Logging out of Cloud Insights logs you out of Cloud Central. You will also be logged out of other NetApp Cloud services that use the Cloud Central sign-in.
