---
sidebar: sidebar
permalink: task_getting_started_with_cloud_insights.html
summary: getting started with Cloud Insights.
---
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

= Getting Started with Cloud Insights

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help

toc::[]

== Setup and Collect data

. Sign in / Sign up at http://cloud.netapp.com
. Create tenant
. Customer account owner invites users to access the tenant
+
The Account owner invites and assigns a role to each user.  Users with the Administrator role can invite other users as well.
+
Once a user accepts the invitation, he or she will be taken to the NetApp Cloud Portal, where they will sign up using the email address in the invitation. If they have an existing account for that email address, they can simply sign in and will then be able to access their Cloud insights tenant.
+
TBD: Link to more Invitation info

. Tenant owner / admin sets up an Acquisition Unit for their tenant.
+
An Acquisition Unit is required to inject data into Cloud Insights. You will need to download and install the acquisition unit software on a server or VM to collect data for Cloud Insights.
+
TBD: Link to AU Install instructions/downloads

. Tenant owner / admin adds data collectors
+
More info on data collectors

. Tenant to troubleshoot data collector failures (data collector details page refactor, June)
+
TBD: troubleshooting info

