---
sidebar: sidebar
permalink: task_invite_users.html
keywords: users, invite, invitation, onboarding
summary: You can invite users, giving them admin, user, or guest access to the tenant
---

= Inviting Users to your Tenant

:toc: macro
:hardbreaks: 
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Account Owner invites users to access the tenant, and assigns a role to each user.  Users with the Administrator role can invite other users as well.

== Inviting users to access the tenant

To Invite a user, in the Cloud Insights tenant, click on *Admin > Account Management* and follow these steps:

. Click the *[+User]* button
. Enter the email addresses for the users you wish to invite.
. Assign a *Role* to these users. Note that all of the users in the email list will receive this Role.
. When finished, click *[Invite]*.
+
Users will have 14 days to accept the invitation. Once a user accepts the invitation, he or she will be taken to the NetApp Cloud Portal, where they will link:task_cloud_insights_onboarding_1.html[sign up] using the email address in the invitation. If they have an existing account for that email address, they can simply sign in and will then be able to access the Cloud Insights tenant.

//**TBD: Define Roles**
