---
sidebar: sidebar
permalink: task_dc_na_ontap.html
keywords: data collector, ontap, clustered ontap
summary: CDOT collector
--- 

= ONTAP Data Management data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

This data collector acquires inventory and performance data from storage systems running ONTAP Data management software using read-only API calls from an administrator account.

== Terminology

Cloud Insights acquires inventory and performance data from the ONTAP Data management software data collector. For each asset type acquired, the most common terminology used for the asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term | Cloud Insights Term
|Disk|Disk
|Raid Group|Disk Group
|Cluster|Storage
|Node|Storage Node
|Aggregate|Storage Pool
|LUN|Volume
|Volume|Internal Volume
|===

== Requirements

The following are requirements to configure and use this data collector:

* You must have access to an account used for read-only API calls.
* Target IP is the cluster management LIF.
* FCP license and mapped/masked volumes required for Cloud Insights discovery.
* CIFS and/or NFS license and CIFS shares or NFS exports required for Cloud Insights NAS discovery.
* Access validation: Telnet or SSH to the cluster management LIF from the acquisition unit, using the username and password.

* For Clustered ONTAP you need the IP cluster management LIF or the management IP of the cluster. Additionally, requires username (with read-only role name to ontapi application to the default Vserver, see below) and password to log into NetApp cluster.
+
To create a read-only user account (may be slightly different on different ONTAP versions), log into the NetApp storage system by using an SSH client and run the following command (case sensitive) and use your own user account variables:
+
 security login role create -role test -cmddirname DEFAULT -access readonly
 security login create - user-or-group-name useraccount -application ontap -authmethod password -role test-vserver storagename

== Configuration 

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|NetApp Management IP |IP address or fully-qualified domain name of the NetApp cluster
|User Name |User name for NetApp cluster
|Password |Password for NetApp cluster 
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Connection Type |HTTPS or HTTP, also displays the default port
|Override Connection Port |If blank, use the default port in the Connection Type field, otherwise enter the connection port to use
|Inventory Poll Interval (min) |Default is 20 minutes.
|Performance Poll Interval (sec)|Default is  300 seconds.
|===


== Troubleshooting
Some things to try if you encounter problems with this data collector:

==== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|Receive 401 HTTP response or 13003 ZAPI error code and ZAPI returns “Insufficient privileges” or “not authorized for this command”| Check username and password, and user privileges/permissions.
|Cluster version is < 8.1| Cluster minimum supported version is 8.1. Upgrade to minimum supported version.
|ZAPI returns "cluster role is not cluster_mgmt LIF"|AU needs to talk to cluster management IP. Check the IP and change to a different IP if necessary
|Error: “7 Mode filers are not supported”| This can happen if you use this data collector to discover 7 mode filer. Change IP to point to cdot filer instead. 
|ZAPI command fails after retry| AU has communication problem with the cluster. Check network, port number, and IP address. User should also try to run a command from command line from the AU machine. 
|AU failed to connect to ZAPI via HTTP| Check whether ZAPI port accepts plaintext. If AU tries to send plaintext to an SSL socket, the communication fails.
|Communication fails with SSLException|AU is attempting to send SSL to a plaintext port on a filer. Check whether the ZAPI port accepts SSL, or use a different port.
|Additional Connection errors:

ZAPI response has error code 13001, “database  is not open”
  
ZAPI error code is 60 and response contains “API did not finish on time”
  
ZAPI response contains “initialize_session() returned NULL environment”
  
ZAPI error code is 14007 and response contains “Node is not healthy”

|Check network, port number, and IP address. User should also try to run a command from command line from the AU machine. 
|===

==== Performance
[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|“Failed to collect performance from ZAPI” error|This is usually due to perf stat not running. Try the following command on each node:

> _system node systemshell -node * -command “spmctl -h cmd –stop; spmctl -h cmd –exec”_
|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].



