---
sidebar: sidebar
permalink: task_create_webhook.html
keywords: webhook, notification, slack, integration
summary: Create monitors to alert on performance or inventory thresholds
---

= Notification using Webhooks

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Webhooks allow users to send alert notifications to various applications using a customized webhook channel.

NOTE: This documentation is considered _Preview_ documentation and is therefore subject to change.

Many commercial applications support webhooks as a standard input interface, for example: Slack, Jira, Zapier, and Twilio all support webhooks. By supporting a generic, customizable webhook channel, Cloud Insights can support many of these delivery channels.

You can create multiple webhook channels, each channel targeted for a different perpuse; a separate application, different recipients, etc. 

The Webhook channel instance is comprised of the following elements:

|===
|Name|Unique name
|URL	|Webhook target URL. The URL will include http/https prefix
|Method	|GET, POST, PUT, HEAD, DELETE, PATCH, OPTIONS - Default is POST
|Payload|Message body
Custom Headers
(optional) allow adding custom headers such as token etc.
|Form-encoded	|Form encoded serialization (Boolean)
|Secrets|A set of secret parameters (api-key, token, password) that will not be visible to users and will be encrypted in the DB. 
A user can embed these parameters to alert fields
|===


To create a webhook, go to *Admin > Notifications* and select the *Webhooks* tab.

