---
sidebar: sidebar
permalink: task_dc_ms_hyperv.html
keywords: data collector, Microsoft, Hyper-V
summary: Configuring Microsoft Hyper-V data collector.
---

= Microsoft Hyper-V data collector

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The Microsoft Hyper-V data collector acquires inventory and performance data from the virtualized server computing environment.

== Terminology

Cloud Insights acquires the following inventory information from the Microsoft Hyper-V (WMI). For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|Virtual Hard Disk|Virtual Disk
|Host|Host
|Virtual Machine|Virtual Machine
|Cluster Shared Volumes (CSV), Partition Volume|Data Store
|Internet SCSI Device, Multi Path SCSI LUN|LUN
|Fiber Channel Port|Port
|===

Note: These are common terminology mappings only and might not represent every case for this data collector. 

== Requirements

The following are required to configure this data collector:

* IP address of Clustering group node
* Local Administrator user & password on the hypervisor 
* Administrative-level user account
* Windows Management Instrumentation (WMI) command, which is the default that is installed by Windows.
* Port requirements: Port 135 via WMI & Dynamic TCP ports assigned 1024-65535 for Windows 2003 and older and 49152-65535 for Windows 2008. 

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Physical Host IP Address|The IP address or fully-qualified domain name for the physical host (hypervisor)
|User Name|Administrator user name for the hypervisor
|Password|Password for the hypervisor 
|NT Domain|The DNS name used by the nodes in the cluster
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Inventory Poll Interval (min)|The default is 20 minutes.
//|Connection Timeout (ms)|The default is 60000 ms. 
|===

           
== Troubleshooting

Additional information on this Data Collector may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].

