---
sidebar: sidebar
<<<<<<< HEAD
permalink: Task_Configure_acquisition_unit.html
keywords: acquisition, Authorization Unit, keyword3, keyword4, keyword5
=======
permalink: Task-Configure-acquisition-unit.html
keywords: acquisition, AU, keyword3, keyword4, keyword5
>>>>>>> 1cb2a67ffed03d405aea9bd7819b3dfa25d1d4d8
summary: A summary.
---
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

= Acquisition Unit Installation Instructions

[.lead]
Acquisition Units collect data from devices in the data center using modules called Data Collectors.


.Before you begin
You must have received the Acquisition unit password in email from NetApp

.About this task

.Steps
. Answer the following prompts:
.. Authorization Unit name (default is the host name where Authorization Unit is being installed)
.. Prompt for Port – Keep as 443
.. Tenant domain name (FQDN)
.. Authorization Unit password (provided previously)
.. Restore key set or generate new key
... On First install ALWAYS answer “Generate New Key”
. Confirm Authorization Unit is running using the following command:
+
“systemctl status acquisition”

.After you finish
You can access the Acquisition Unit logs at /var/netapp/oci/acq/acq.log
