---
sidebar: sidebar
permalink: concept_create_query.html
summary: How to create a query
keywords: query, queries, create
---

= Creating a Query

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a query to enable you to search the assets in your environment at a granular level. Queries enable you to slice data by adding filters and then sorting the results to view inventory and performance data in one view.

For example, you can create a query for volumes, add a filter to find particular storages associated with the selected volume, add a filter to find a particular annotation, such as _Tier 1_, on the selected storages, and finally add another filter to find all storages with _IOPS - Read (IO/s)_ greater than 25. When the results are displayed, you can then sort the columns of information associated with the query in ascending or descending order.

When a new data collector is added which acquires assets, or any annotation or application assignments are made, you can query for those assets, annotations, or applications after the queries are indexed, which occurs at a regularly scheduled interval.

.Steps
. Log in to the OnCommand Insight web UI.
. Click Queries and select + New Query.
. Click Select Resource Type and select a type of asset.
+
When a resource is selected for a query, a number of default columns are automatically displayed; you can remove these columns or add new ones at any time.
. In the Name text box, type the name of the asset or type a portion of text to filter through the asset names.
. You can use any of the following alone or combined to refine your search in any text box on the New Query page:
+
* An asterisk enables you to search for everything. For example,
  vol*rhel
+
displays all resources that start with "vol" and end with "rhel".
+
* The question mark enables you to search for a specific number of characters. For example,
  BOS-PRD??-S12
+
displays BOS-PRD12-S12, BOS-PRD13-S12, and so on.
+
* The OR operator enables you to specify multiple entities. For example,
  FAS2240 OR CX600 OR FAS3270
+
finds multiple storage models.
+
* The NOT operator allows you to exclude text from the search results. For example,
  NOT EMC*
+
finds everything that does not start with "EMC". You can use
  NOT *
+
to display fields that contain no value.
. Click  to display the assets.
. To add a criteria, click , and do either of the following:
.. Type to search for a specific criteria and then select it.
.. Scroll down the list and select a criteria.
.. Enter a range of values if you choose a performance metric like IOPS - Read (IO/s).
+
Default annotations provided by Insight are indicated by ; it is possible to have annotations with duplicate names.
+
A column is added to the Query results list for the criteria and the results of the query in the list updates.
+
Optionally, you can click  to remove an annotation or performance metric from the query results.
For example, if your query shows maximum latency and maximum throughput for datastores and you want to show only maximum latency in the query results list, click this button, and clear the Throughput - Max check box. The Throughput - Max (MB/s) column is removed from the Query results list.
+
NOTE: Depending on the number of columns displayed in the query results table, you may not be able to view additional added columns. You can remove one or more columns until your desired columns become visible.
. Click Save, enter a name for the query, and click Save again.

If you have an account with an administrator role, you can create dashboards. A dashboard can comprise any of the widgets from the Widget Library, several of which let you represent query results in a dashboard. For more information about dashboards, see the topics under Dashboards.
