---
sidebar: sidebar
permalink: task_view_configured_data_collectors.html
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling
summary: A summary.
---

= Managing configured data collectors

[.lead]

The Installed Data Collectors page provides access to the data collectors that have been configured for Cloud Insights. You can use this page to modify existing data collectors.   


.Steps

. In the Cloud Insights menu, click *Admin > Data Collectors*
+
The Available Data Collectors screen is displayed. 
. Click *Installed Data Collectors* 
+
A list of all of the installed Data Collectors is displayed. The list provides collector 
name, status, the IP address the collector is accessing, and when data was last acquired 
from the a device. Action that can be performed on this screen include:

* Control polling
* Change data collector credentials  
* Clone data collectors

== Controlling Data Collector polling

After making a change to a data collector, you might want it to poll immediately to check 
your changes, or you might want to postpone the data collection on a data collector for one, 
three, or five days while you work on a problem.

.Steps

. In the Cloud Insights menu, click *Admin > Data Collectors*
. Click *Installed Data Collectors*
. Select the check box to the left of the Data Collector you want to change 
. Click *Bulk Actions* and select the polling action you want to take. 
+
Bulk actions can be performed simultaneously on multiple Data Collectors. Select the data 
collectors, and chose the action to perform from the *Bulk Action* menu. 

== Editing data collector information 

You can edit existing data collector setup information. 

.Steps

. In the Cloud Insights menu, click *Admin > Data Collectors*
. Click *Installed Data Collectors*
. Select the check box to the left of the data collector you want to change.
. In the options menu to the right of the selected data collector, click *Edit*. 
+
The Edit Collector dialog is opened.

. Enter the changes and click *Test Configuration* to test the new configuration or click *Save* to save the configuration. 

== Cloning data collectors

Using the clone facility, you can quickly add a data source that has the same credentials 
and attributes as another data source. Cloning allows you to easily configure multiple 
instances of the same device type.

.Steps

. In the Cloud Insights menu, click *Admin > Data Collectors*
. Click *Installed Data Collectors*
. Click the check box to the left of the data collector you want to copy. 
. In the options menu to the right of the selected data collector, click *Clone*. 
+
The Clone Data Collector dialog is displayed.
. Enter new information in the required fields. 
. Click *Save* 

.After you finish 

The clone operation copies all other attributes and settings to create the new data collector. 

== Performing bulk actions on data collectors


