---
sidebar: sidebar
permalink: task_dc_brocade_rest.html
keywords: data collector, Brocade, FC switch, FOS, Rest
summary: Configuring Brocade FOS REST data collector.
---

= Brocade FOS REST Data Collector
:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead] 
Cloud Insights uses the Brocade FOS REST collector to discover inventory and performance for Brocade switch devices running FabricOS (FOS) firmware 8.2 and later. 

By default, this collector will attempt to discover all the FOS devices that are a part of all the fabrics the switch is part of.

== Terminology 

Cloud Insights acquires the following inventory information from the Brocade FOS REST data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===

|Vendor/Model Term|Cloud Insights Term

|Switch|Switch
|Port|Port
|Virtual Fabric, Physical Fabric|Fabric
|Zone|Zone
|Logical Switch|Logical Switch
|Virtual Volume|Volume
|LSAN Zone|IVR Zone
|===

Note: These are common terminology mappings only and might not represent every case for this data collector.

== Requirements

* There must be IP connectivity to all switches in the fabric. If you select the _Discover all switches in the fabric_ check box, Cloud Insights identifies all the switches in the fabric; however, it needs IP connectivity to these additional switches to discover them.
* The same account is needed globally across all switches in the fabric. You can use PuTTY (open source terminal emulator) to confirm access.

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Switch IP|IP address or fully-qualified domain name of the EFC Server
|User Name|User name for the switch
|Password|Password for the switch
|===

== Advanced configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Excluded Devices|Comma-separated list of device IDs to exclude from polling.
|Inventory Poll Interval (min)| Interval between inventory polls. The default is 60.
|Discover all switches in the fabric|Select to discover all switches in the fabric.
|Choose Favoring HBA vs. Zone Aliases|Choose whether to favor HBA or zone aliases.
|Connection type| HTTP or HTTPS.
|Override TCP Port|Specify a port if not using the default.
|Performance Poll Interval (sec)|Interval between performance polls. The default is 300.

|===


== Troubleshooting
Some things to try if you encounter problems with this data collector:

=== Inventory

[cols=2*, options="header", cols"50,50"]
|===

|Problem:|Try this:

|The inventory acquisition of the Brocade datasource fails with the error:

<date> <time> ERROR [com.onaro.sanscreen.acquisition.framework.datasource.BaseDataSource]   Error 2 out of 2: <datasource name> [Internal error] - Unable to generate the model for device <IP>. Error detecting prompt ([Device name <name>]: Unable to generate the model for device <IP>. Error detecting prompt)
|The issue may be caused when the Brocade switch takes too long to return with a prompt, exceeding the default timeout of 5 seconds.
In the data collector's Advanced Configuration settings in Cloud Insights, try increasing the  _SSH Banner Wait Timeout (sec)_ to a higher value.

|Error: “Cloud Insights received Invalid Chassis Role” |Check that the user configured in this data source has been granted the chassis role permission.
|Error: "Mismatched Chassis IP Address" |Change the data source configuration to use chassis IP address.
|Receive a message that more than 1 node is logged into the Access Gateway port| Check that the NPV device is operating correctly and that all connected WWNs are expected. Do not directly acquire the NPV device. Instead, acquisition of the core fabric switch will collect the NPV device data.

|Performance collection fails with "Timed out during sending SNMP request".
|Depending on query variables and switch configuration, some queries may exceed the default timeout.  link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Insights/Cloud_Insight_Brocade_data_source_fails_performance_collection_with_a_timeout_due_to_default_SNMP_configuration[Learn More]. 


|===

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:reference_data_collector_support_matrix.html[Data Collector Support Matrix].
