---
sidebar: sidebar
permalink: task_dc_hds_ops_center.html
keywords: data collector, Hitachi Ops Center
summary: Configuring HDS COps Center data collector.
---

= Hitachi Ops Center data collector

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/



[.lead] 

This data collector uses Hitachi Ops Center's integrated suite of applications to access inventory and performance data of multiple storage devices.

== Terminology 

Cloud Insights acquires the following inventory information from this data collector. For each asset type acquired by Cloud Insights, the most common terminology used for this asset is shown. When viewing or troubleshooting this data collector, keep the following terminology in mind:

[cols=2*, options="header", cols"50,50"]
|===
|Vendor/Model Term|Cloud Insights Term 
|Storage Systems|Storage
|Volume|Volume
|Parity Groups|Storage Pool(RAID), Disk Groups
|Disk|Disk
|Storage Pool|Storage Pool(Thin, SNAP)
|External Parity Groups|Storage Pool(Backend), Disk Groups
|Port|Storage Node → Controller Node → Port
|Host Groups|Volume Mapping and Masking
|Volume Pairs|Storage Synchronization
|===

Note: These are common terminology mappings only and might not represent every case for this data collector. 

== Inventory Requirements

You must have the following in order to collect inventory data:

* IP address of the Ops Center server
* Read-only user name and password for the Ops Center software and peer privileges

////
== Performance requirements 

The following requirements must be met in order to collect performance data:

* HDS USP, USP V, and VSP performance 
** Performance Monitor must be licensed.
** Monitoring switch must be enabled. 
** The Export Tool (Export.exe) must be copied to the Cloud Insights AU.
** The Export Tool version must match the microcode version of the target array.

* AMS performance:
** NetApp strongly recommends creating a dedicated service account on AMS arrays for Cloud Insights to use to retrieve performance data. Storage Navigator only allows a user account one concurrent login to the array. Having Cloud Insights use the same user account as management scripts or HiCommand may result in Cloud Insights, management scripts, or HiCommand being unable to communicate to the array due to the one concurrent user account login limit
** Performance Monitor must be licensed.
** The Storage Navigator Modular 2 (SNM2) CLI utility needs to be installed on the Cloud Insights AU. 
////

== Configuration

[cols=2*, options="header", cols"50,50"]
|===
|Field|Description
|Hitachi Ops Center IP Address |IP address or fully-qualified domain name of the Ops Center server 
|User Name |User name for the Ops Center server. 
|Password|Password used for the Ops Center server. 
|===

== Advanced configuration

|===
|Field|Description
|Connection Type|HTTPS (port 443) is the default
|Override TCP Port |Specify the port to use if not the default 
|Inventory Poll Interval (min)|	Interval between inventory polls. The default is 40.  
|Choose 'Exclude' or 'Include' to specify a list|Specify whether to include or exclude the array list below when collecting data.
|Filter device List|Comma-separated list of device ID's or array names to include or exclude
|Performance Poll Interval (sec)|Interval between performance polls. The default is 300.
|===

////
== Troubleshooting
Some things to try if you encounter problems with this data collector:

==== Inventory

[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|Error: User does not have enough permission
|Use a different user account that has more privilege or increase the privilege of user account configured in the data collector
|Error: Storages list is empty. Either devices are not configured or the user does not have enough permission
|*	Use DeviceManager to check if the devices are configured.
* Use a different user account that has more privilege, or increase the privilege of the  user account
|Error: HDS storage array was not refreshed for some days
|Investigate why this array is not being refreshed in HDS HiCommand.
|===

==== Performance
[cols=2*, options="header", cols"50,50"]
|===
|Problem:|Try this:
|Error:
* Error executing export utility
* Error executing external command
|* Confirm that Export Utility is installed on the Cloud Insights Acquisition Unit
* Confirm that Export Utility location is correct in the data collector configuration
* Confirm that the IP of the USP/R600 array is correct in the configuration of the data collector
* Confirm that the User name and password are correct in the configuration of the data collector
* Confirm that Export Utility version is compatible with storage array micro code version
* From the Cloud Insights Acquisition Unit, open a CMD prompt and do the following:
- Change the directory to the configured installation directory
- Try to make a connection with the configured storage array by executing batch file runWin.bat
|Error: Export tool login failed for target IP
|* Confirm that username/password is correct
* Create a user ID mainly for this HDS data collector
* Confirm that no other data collectors are configured to acquire this array
|Error: Export tools logged "Unable to get time range for monitoring".
|* Confirm performance monitoring is enabled on the array.
* Try invoking the export tools outside of Cloud Insights to confirm the problem lies outside of Cloud Insights.
|Error:
* Configuration error: Storage Array not supported by Export Utility
* Configuration error: Storage Array not supported by Storage Navigator Modular CLI
|* Configure only supported storage arrays.
* Use “Filter Device List” to exclude unsupported storage arrays.
|Error:
* Error executing external command
* Configuration error: Storage Array not reported by Inventory
* Configuration error:export folder does not contains jar files
|* Check Export utility location.
* Check if Storage Array in question is configured in HiCommand server
* Set Performance poll interval as multiple of 60 seconds.
|Error:
* Error Storage navigator CLI
* Error executing auperform command
* Error executing external command
|* Confirm that Storage Navigator Modular CLI is installed on the Cloud Insights Acquisition Unit
* Confirm that Storage Navigator Modular CLI location is correct in the data collector configuration
* Confirm that the IP of the WMS/SMS/SMS array is correct in the configuration of the data collector
* Confirm that Storage Navigator Modular CLI version is compatible with micro code version of storage array configured in the data collector
* From the Cloud Insights Acquisition Unit, open a CMD prompt and do the following:
- Change the directory to the configured installation directory
- Try to make a connection with the configured storage array by executing following command “auunitref.exe”
|Error: Configuration error: Storage Array not reported by Inventory
|Check if Storage Array in question is configured in HiCommand server
|Error:
* No Array is registered with the Storage Navigator Modular 2 CLI
* Array is not registered with the Storage Navigator Modular 2 CLI
* Configuration error: Storage Array not registered with StorageNavigator Modular CLI
|* Open Command prompt and change directory to the configured path
* Run the command “set=STONAVM_HOME=.”
* Run the command “auunitref”
* Confirm that the command output contains details of the array with IP
* If the output does not contain the array details then register the array with Storage Navigator CLI:
    - Open Command prompt and change directory to the configured path
    - Run the command “set=STONAVM_HOME=.”
    - Run command “auunitaddauto -ip ${ip}”. Replace ${ip} with real IP
|===
////

Additional information may be found from the link:concept_requesting_support.html[Support] page or in the link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf[Data Collector Support Matrix].

