---
sidebar: sidebar
permalink: task_troubleshooting_linux_acquisition_unit_problems.html
summary: Troubleshooting tips for Acquisition Unit problems.
keywords: AU, acquisition unit, trioubleshooting
---

= Troubleshooting Acquisition Unit Problems on Linux

:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Here you will find suggestions for troubleshooting problems with Acquisition Units on a Linux server. 

|===
|*Problem:* | *Try this:* 
|AU status on the *Admin > Data Collectors* page in the *Acquisition Units* tab displays "Certificate Expired” or “Certificate Revoked” .
|Click on the menu to the right of the AU and select *Restore Connection*. Follow the instructions to restore your Acquisition Unit:
1. Issue the given command on the AU server/VM to stop the Acquisition Unit service. You can click the clipboard icon in the command window to quickly copy the command to the clipboard.
2. Copy the displayed token and paste it into a new file named "token".
3. Place this file in the /var/lib/netapp/cloudinsights/acq/conf/ folder.
4. Use the given command to start the Acquisition Unit service.
|Installation fails on SELinux|When the AU is installed on SELinux, SE should be either disabled or set to permissive mode. Once the installation is complete, enforcing mode can be enabled.   
|Server Requirements not met | Ensure that your Acquisition Unit server or VM meets  link:concept_acquisition_unit_requirements.html[requirements]
|Network Requirements not met |Ensure that your Acquisition Unit server/VM can access your Cloud Insights environment (<environment-name>.c01.cloudinsights.netapp.com) through SSL connection over port 443 
|Proxy Server not configured properly | Follow the link:task_configure_acquisition_unit.html#Setting_proxy_environment_variables[instructions] under “Have a Proxy Server?” in the Add an Acquisition Unit box. 
|Linux: missing library / file not found| Ensure that your Linux Acquisition Unit server/VM has all necessary libraries. For example, you must have the _unzip_ library installed on the server. To install the _unzip_ library, run the command _*sudo yum install unzip*_ before running the Acquisition Unit install script
|Permission issues| Be sure you are logged in as a user with _sudo_ permissions

|Acquisition Not Running:
| Gather the acq.log from /opt/netapp/cloudinsights/acq/logs (Linux)
Restart the Acquisition Service: sudo cloudinsights-service.sh restart acquisition
|Data Collection Issues:
|Get an Error Report from the Data Collector landing page, go to the drop down next to the “Edit” icon and select “Error Report”
|===

////
Moving Data Collectors to Different Acquisition Units:
•	What is the proper process for a customer to do this?  They have to retype their passwords or go into the security admin tool to transfer the keys?
////

=== More About Proxy/Firewall

Proxies and firewalls require special consideration when working with many applications, including Cloud Insights, in situations where the application does not easily co-exist with SSL. In the case of Cloud Insights, the Acquisition Unit (AU) has a digital certificate that expects to negotiate with Cloud Insights. Proxies and firewalls affect this negotiation.

In this case, the Cloud Insights environment must be added to a whitelist in the proxy configuration. The format and setup of this whitelist varies according to your proxy environemnt and tools, but in general you must add the URLs of the Cloud Insights servers to this whitelist in order to allow the AU to properly communicate with those servers.

The simplest way to do this is to whitelist the Cloud Insights domain itself:

 *.cloudinsights.netapp.com
 
 MENTION 
 Specific URLs?


