---
sidebar: sidebar
permalink: task_getting_started_with_cloud_cost.html
summary: Getting started with Cloud Cost.
keywords: analysis, cost, analyzer
---

= Getting started with Cloud Cost 

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Cloud Cost Analyzer Cloud Analyzer provides a detailed cost analysis of past, present, and estimated spend, providing deep cross-cloud and cross-account visibility. The Cloud Cost dashboard delivers a clear view of your organization's entire cloud expenses and a drill down into individual workloads, accounts, and services.

Cloud Cost can help with the following major challenges:

* Tracking and monitoring of your cloud expenses
* Identifying waste and potential optimization points
* Delivering executable action items

You must have CLoud Insights Administrator or Accunt Owner permissions to configure or view Cloud Cost


Notes:
Only US-Based Cloud Insights will see CC
All Editions (Basic, Std, Premium
Only Admin/Acct Owner

Onboarding - configure AWS account (once)
All Admin users can then see the CC page

